#!/bin/bash

go mod tidy

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
    echo "no go files were stashed"
    exit 0
fi

go vet ./...
if [[ $? != 0 ]]; then
  echo "Go vet failed"
  exit 1
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
  goimports -w $FILE
  git add $FILE
  
done

if ! $PASS; then
  printf "FAIL: Pre-commit pipeline failed\n"
  exit 1
else
  printf "Pre-commit pipeline succeeded\n"
fi

exit 0

