version: '3'

vars:
  PROTOBUF_VERSION: "32.1"

tasks:
  ################# Development Tools ####################
  # Additional resources:
  # - https://go.dev/doc/install
  # - https://protobuf.dev/getting-started/gotutorial/
  # - https://protobuf.dev/installation/
  # - https://go.dev/doc/tutorial/govulncheck
  tools:
    desc: "Download tools required for development"
    deps: [install-protobuf-compiler, install-go-protoc-modules, install-go-vulnerability-check]
    cmds:
      - protoc --version && protoc-gen-go --version && govulncheck --version

  run-benchmarks:
    desc: "Command runs benchmarks. For this to work, you need to have the deployment repository in the same parent directory as this repository."
    cmds:
      - CRYPTO_BROKER_PROFILES_DIR=$(pwd)/example-profiles go test ./... -run=^$ -bench=.

  # Public task to install the pre-built protobuf compiler depending on the architecture
  install-protobuf-compiler:
    desc: "Download and install pre-built protobuf compiler"
    cmds:
      - task: install-protobuf-compiler-linux-amd64
      - task: install-protobuf-compiler-darwin

  install-protobuf-compiler-linux-amd64:
    desc: "Download and install pre-built protobuf compiler for Linux"
    internal: true
    platforms: ["linux/amd64"]
    cmds:
      # Create temporary download folder
      - mkdir tmp-download
      # Download specified version
      - cd tmp-download && curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v{{.PROTOBUF_VERSION}}/protoc-{{.PROTOBUF_VERSION}}-linux-x86_64.zip
      # Unzip download
      - cd tmp-download && unzip protoc-{{.PROTOBUF_VERSION}}-linux-x86_64.zip -d $HOME/.local/share/protobuf/
      # Remove temporary download folder
      - rm -rf tmp-download
      # Add path to .bashrc if it does not already exists
      - grep -qx 'export PATH="$PATH:$HOME/.local/share/protobuf/bin"' ~/.bashrc || echo 'export PATH="$PATH:$HOME/.local/share/protobuf/bin"' >> ~/.bashrc
      # Reload .bashrc
      - source $HOME/.bashrc

  install-protobuf-compiler-darwin:
    desc: "Download and install protobuf compiler for Apple/macOS"
    internal: true
    platforms: ["darwin"]
    cmds:
      - brew install protobuf

  # Public task to install Go modules needed for protobuf and gRPC generation
  install-go-protoc-modules:
    desc: "Install Go modules for protobuf and gRPC support"
    cmds:
      - task: install-go-protoc-modules-linux-amd64
      - task: install-go-protoc-modules-darwin

  install-go-protoc-modules-linux-amd64:
    desc: "Install Go modules for protobuf and gRPC support for Linux"
    internal: true
    deps: [bash-add-go-path]
    platforms: ["linux/amd64"]
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

  install-go-protoc-modules-darwin:
    desc: "Install Go modules for protobuf and gRPC support for Apple/macOS"
    internal: true
    platforms: ["darwin"]
    cmds:
      - brew install protoc-gen-go
      - brew install protoc-gen-go-grpc

  bash-add-go-path:
    desc: "Add Go binary folder to .bashrc if it does not already exists"
    internal: true
    platforms: ["linux/amd64"]
    cmds:
      - grep -qx 'export PATH="$PATH:$(go env GOPATH)/bin"' ~/.bashrc || echo 'export PATH="$PATH:$(go env GOPATH)/bin"' >> ~/.bashrc
      - source ~/.bashrc

  # Public task to install Go vulnerability checking tool
  install-go-vulnerability-check:
    desc: "Install Go vulnerability checking tool"
    cmds:
      - task: install-go-vulnerability-check-linux-amd64
      - task: install-go-vulnerability-check-darwin

  install-go-vulnerability-check-linux-amd64:
    desc: "Install Go vulnerability checking tool for Linux"
    internal: true
    deps: [bash-add-go-path]
    platforms: ["linux/amd64"]
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  install-go-vulnerability-check-darwin:
    desc: "Install Go vulnerability checking tool for Apple/macOS"
    internal: true
    platforms: ["darwin"]
    cmds:
      - brew install govulncheck

  ################# Crypto Broker Server Execution ####################
  cleanup-socket:
    desc: "Cleans up the Crypto Broker server socket"
    cmds:
      - rm -rf /tmp/cryptobroker.sock

  run:
    desc: "Runs Crypto Broker server locally"
    deps: [build]
    cmds:
      - defer: {task: cleanup-socket}
      - CRYPTO_BROKER_PROFILES_DIR=$(pwd)/example-profiles ./bin/cryptobroker-server

  ################# Build Crypto Broker Server ####################
  build:
    desc: "Builds Crypto Broker server binary"
    cmds:
      - cmd: go build -o bin/cryptobroker-server cmd/server/server.go
    sources:
      - cmd/server/server.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/cryptobroker-server

  build-docker:
    desc: "Builds Crypto Broker server in a Docker image"
    vars:
      TAG: '{{.TAG | default "latest"}}'
    dotenv: ['.env']
    cmds:
      - docker buildx build --build-arg="CRYPTO_BROKER_PROFILES_DIR=example-profiles" -t ghcr.io/open-crypto-broker/server:{{.TAG}} .

  proto:
    desc: "Generates Go stubs from proto files"
    cmds:
      - git submodule update --init --recursive
      - protoc --go_out=. --go-grpc_out=. protobuf/messages.proto

  ################# Continuous Improvement Tasks ####################
  check-dependencies:
    desc: "Set the dependencies"
    cmds:
      - go mod tidy && go mod verify

  format:
    desc: "Apply formatting rules to Go code"
    cmds:
      - go fmt ./...

  lint:
    desc: "Apply linting to Go code"
    cmds:
      - go vet ./...

  unit-test:
    desc: "Run unit-tests"
    cmds:
      - CRYPTO_BROKER_PROFILES_DIR=$(pwd)/example-profiles go test ./... -skip E2E -cover
      - CRYPTO_BROKER_PROFILES_DIR=$(pwd)/example-profiles go test ./... -run E2E -cover

  vulnerability-check:
    desc: "Run vulnerability check"
    deps: [install-go-vulnerability-check]
    cmds:
      - govulncheck ./...

  ci:
    desc: "Runs continuous integration checks on source code"
    dotenv: ['.env']
    cmds:
      - task: check-dependencies
      - task: format
      - task: lint
      - task: unit-test
      - task: vulnerability-check
