// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CryptoGrpcClient is the client API for CryptoGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoGrpcClient interface {
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type cryptoGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoGrpcClient(cc grpc.ClientConnInterface) CryptoGrpcClient {
	return &cryptoGrpcClient{cc}
}

func (c *cryptoGrpcClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, "/CryptoBroker.CryptoGrpc/Hash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoGrpcClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/CryptoBroker.CryptoGrpc/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoGrpcServer is the server API for CryptoGrpc service.
// All implementations must embed UnimplementedCryptoGrpcServer
// for forward compatibility
type CryptoGrpcServer interface {
	Hash(context.Context, *HashRequest) (*HashResponse, error)
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	mustEmbedUnimplementedCryptoGrpcServer()
}

// UnimplementedCryptoGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedCryptoGrpcServer struct {
}

func (UnimplementedCryptoGrpcServer) Hash(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hash not implemented")
}
func (UnimplementedCryptoGrpcServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedCryptoGrpcServer) mustEmbedUnimplementedCryptoGrpcServer() {}

// UnsafeCryptoGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoGrpcServer will
// result in compilation errors.
type UnsafeCryptoGrpcServer interface {
	mustEmbedUnimplementedCryptoGrpcServer()
}

func RegisterCryptoGrpcServer(s *grpc.Server, srv CryptoGrpcServer) {
	s.RegisterService(&_CryptoGrpc_serviceDesc, srv)
}

func _CryptoGrpc_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoGrpcServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoBroker.CryptoGrpc/Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoGrpcServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoGrpc_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoGrpcServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoBroker.CryptoGrpc/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoGrpcServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CryptoGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CryptoBroker.CryptoGrpc",
	HandlerType: (*CryptoGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hash",
			Handler:    _CryptoGrpc_Hash_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _CryptoGrpc_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/messages.proto",
}

// CryptoGrpcDevClient is the client API for CryptoGrpcDev service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoGrpcDevClient interface {
	Benchmark(ctx context.Context, in *BenchmarkRequest, opts ...grpc.CallOption) (*BenchmarkResponse, error)
	FakeEndpoint(ctx context.Context, in *FakeEndpointRequest, opts ...grpc.CallOption) (*FakeEndpointResponse, error)
}

type cryptoGrpcDevClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoGrpcDevClient(cc grpc.ClientConnInterface) CryptoGrpcDevClient {
	return &cryptoGrpcDevClient{cc}
}

func (c *cryptoGrpcDevClient) Benchmark(ctx context.Context, in *BenchmarkRequest, opts ...grpc.CallOption) (*BenchmarkResponse, error) {
	out := new(BenchmarkResponse)
	err := c.cc.Invoke(ctx, "/CryptoBroker.CryptoGrpcDev/Benchmark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoGrpcDevClient) FakeEndpoint(ctx context.Context, in *FakeEndpointRequest, opts ...grpc.CallOption) (*FakeEndpointResponse, error) {
	out := new(FakeEndpointResponse)
	err := c.cc.Invoke(ctx, "/CryptoBroker.CryptoGrpcDev/FakeEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoGrpcDevServer is the server API for CryptoGrpcDev service.
// All implementations must embed UnimplementedCryptoGrpcDevServer
// for forward compatibility
type CryptoGrpcDevServer interface {
	Benchmark(context.Context, *BenchmarkRequest) (*BenchmarkResponse, error)
	FakeEndpoint(context.Context, *FakeEndpointRequest) (*FakeEndpointResponse, error)
	mustEmbedUnimplementedCryptoGrpcDevServer()
}

// UnimplementedCryptoGrpcDevServer must be embedded to have forward compatible implementations.
type UnimplementedCryptoGrpcDevServer struct {
}

func (UnimplementedCryptoGrpcDevServer) Benchmark(context.Context, *BenchmarkRequest) (*BenchmarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Benchmark not implemented")
}
func (UnimplementedCryptoGrpcDevServer) FakeEndpoint(context.Context, *FakeEndpointRequest) (*FakeEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FakeEndpoint not implemented")
}
func (UnimplementedCryptoGrpcDevServer) mustEmbedUnimplementedCryptoGrpcDevServer() {}

// UnsafeCryptoGrpcDevServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoGrpcDevServer will
// result in compilation errors.
type UnsafeCryptoGrpcDevServer interface {
	mustEmbedUnimplementedCryptoGrpcDevServer()
}

func RegisterCryptoGrpcDevServer(s *grpc.Server, srv CryptoGrpcDevServer) {
	s.RegisterService(&_CryptoGrpcDev_serviceDesc, srv)
}

func _CryptoGrpcDev_Benchmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BenchmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoGrpcDevServer).Benchmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoBroker.CryptoGrpcDev/Benchmark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoGrpcDevServer).Benchmark(ctx, req.(*BenchmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoGrpcDev_FakeEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FakeEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoGrpcDevServer).FakeEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoBroker.CryptoGrpcDev/FakeEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoGrpcDevServer).FakeEndpoint(ctx, req.(*FakeEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CryptoGrpcDev_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CryptoBroker.CryptoGrpcDev",
	HandlerType: (*CryptoGrpcDevServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Benchmark",
			Handler:    _CryptoGrpcDev_Benchmark_Handler,
		},
		{
			MethodName: "FakeEndpoint",
			Handler:    _CryptoGrpcDev_FakeEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/messages.proto",
}
