// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protobuf/messages.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Output formats
type HashOutputFormat int32

const (
	HashOutputFormat_HEX HashOutputFormat = 0
	HashOutputFormat_RAW HashOutputFormat = 1
)

// Enum value maps for HashOutputFormat.
var (
	HashOutputFormat_name = map[int32]string{
		0: "HEX",
		1: "RAW",
	}
	HashOutputFormat_value = map[string]int32{
		"HEX": 0,
		"RAW": 1,
	}
)

func (x HashOutputFormat) Enum() *HashOutputFormat {
	p := new(HashOutputFormat)
	*p = x
	return p
}

func (x HashOutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashOutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_messages_proto_enumTypes[0].Descriptor()
}

func (HashOutputFormat) Type() protoreflect.EnumType {
	return &file_protobuf_messages_proto_enumTypes[0]
}

func (x HashOutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashOutputFormat.Descriptor instead.
func (HashOutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{0}
}

type SignOutputFormat int32

const (
	SignOutputFormat_DER SignOutputFormat = 0
	SignOutputFormat_PEM SignOutputFormat = 1
)

// Enum value maps for SignOutputFormat.
var (
	SignOutputFormat_name = map[int32]string{
		0: "DER",
		1: "PEM",
	}
	SignOutputFormat_value = map[string]int32{
		"DER": 0,
		"PEM": 1,
	}
)

func (x SignOutputFormat) Enum() *SignOutputFormat {
	p := new(SignOutputFormat)
	*p = x
	return p
}

func (x SignOutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignOutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_messages_proto_enumTypes[1].Descriptor()
}

func (SignOutputFormat) Type() protoreflect.EnumType {
	return &file_protobuf_messages_proto_enumTypes[1]
}

func (x SignOutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignOutputFormat.Descriptor instead.
func (SignOutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{1}
}

// Meta-structures shared across other messages and functions
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceContext  *TraceContext          `protobuf:"bytes,3,opt,name=traceContext,proto3,oneof" json:"traceContext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_protobuf_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetTraceContext() *TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

// Trace context for manual propagation
type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=spanId,proto3" json:"spanId,omitempty"`
	TraceFlags    string                 `protobuf:"bytes,3,opt,name=traceFlags,proto3" json:"traceFlags,omitempty"`
	TraceState    string                 `protobuf:"bytes,4,opt,name=traceState,proto3" json:"traceState,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_protobuf_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TraceContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceContext) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *TraceContext) GetTraceFlags() string {
	if x != nil {
		return x.TraceFlags
	}
	return ""
}

func (x *TraceContext) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

func (x *TraceContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// HashData request and response messages
type HashDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OutputFormat  HashOutputFormat       `protobuf:"varint,4,opt,name=outputFormat,proto3,enum=CryptoBroker.HashOutputFormat" json:"outputFormat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashDataRequest) Reset() {
	*x = HashDataRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashDataRequest) ProtoMessage() {}

func (x *HashDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashDataRequest.ProtoReflect.Descriptor instead.
func (*HashDataRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{2}
}

func (x *HashDataRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *HashDataRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *HashDataRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HashDataRequest) GetOutputFormat() HashOutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return HashOutputFormat_HEX
}

type HashDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashAlgorithm string                 `protobuf:"bytes,2,opt,name=hashAlgorithm,proto3" json:"hashAlgorithm,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to HashValue:
	//
	//	*HashDataResponse_HashValueHex
	//	*HashDataResponse_HashValueRaw
	HashValue     isHashDataResponse_HashValue `protobuf_oneof:"hashValue"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashDataResponse) Reset() {
	*x = HashDataResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashDataResponse) ProtoMessage() {}

func (x *HashDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashDataResponse.ProtoReflect.Descriptor instead.
func (*HashDataResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{3}
}

func (x *HashDataResponse) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

func (x *HashDataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HashDataResponse) GetHashValue() isHashDataResponse_HashValue {
	if x != nil {
		return x.HashValue
	}
	return nil
}

func (x *HashDataResponse) GetHashValueHex() string {
	if x != nil {
		if x, ok := x.HashValue.(*HashDataResponse_HashValueHex); ok {
			return x.HashValueHex
		}
	}
	return ""
}

func (x *HashDataResponse) GetHashValueRaw() []byte {
	if x != nil {
		if x, ok := x.HashValue.(*HashDataResponse_HashValueRaw); ok {
			return x.HashValueRaw
		}
	}
	return nil
}

type isHashDataResponse_HashValue interface {
	isHashDataResponse_HashValue()
}

type HashDataResponse_HashValueHex struct {
	HashValueHex string `protobuf:"bytes,4,opt,name=hashValueHex,proto3,oneof"`
}

type HashDataResponse_HashValueRaw struct {
	HashValueRaw []byte `protobuf:"bytes,5,opt,name=hashValueRaw,proto3,oneof"`
}

func (*HashDataResponse_HashValueHex) isHashDataResponse_HashValue() {}

func (*HashDataResponse_HashValueRaw) isHashDataResponse_HashValue() {}

// SignCertificate response and request messages
type SignCertificateRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Profile               string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Csr                   string                 `protobuf:"bytes,2,opt,name=csr,proto3" json:"csr,omitempty"`
	CaPrivateKey          string                 `protobuf:"bytes,3,opt,name=caPrivateKey,proto3" json:"caPrivateKey,omitempty"`
	CaCert                string                 `protobuf:"bytes,4,opt,name=caCert,proto3" json:"caCert,omitempty"`
	Metadata              *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ValidNotBefore        *uint64                `protobuf:"varint,6,opt,name=validNotBefore,proto3,oneof" json:"validNotBefore,omitempty"`
	ValidNotAfter         *uint64                `protobuf:"varint,7,opt,name=validNotAfter,proto3,oneof" json:"validNotAfter,omitempty"`
	Subject               *string                `protobuf:"bytes,8,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	CrlDistributionPoints []string               `protobuf:"bytes,9,rep,name=crlDistributionPoints,proto3" json:"crlDistributionPoints,omitempty"`
	OutputFormat          SignOutputFormat       `protobuf:"varint,10,opt,name=outputFormat,proto3,enum=CryptoBroker.SignOutputFormat" json:"outputFormat,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SignCertificateRequest) Reset() {
	*x = SignCertificateRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCertificateRequest) ProtoMessage() {}

func (x *SignCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCertificateRequest.ProtoReflect.Descriptor instead.
func (*SignCertificateRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{4}
}

func (x *SignCertificateRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SignCertificateRequest) GetCsr() string {
	if x != nil {
		return x.Csr
	}
	return ""
}

func (x *SignCertificateRequest) GetCaPrivateKey() string {
	if x != nil {
		return x.CaPrivateKey
	}
	return ""
}

func (x *SignCertificateRequest) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *SignCertificateRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SignCertificateRequest) GetValidNotBefore() uint64 {
	if x != nil && x.ValidNotBefore != nil {
		return *x.ValidNotBefore
	}
	return 0
}

func (x *SignCertificateRequest) GetValidNotAfter() uint64 {
	if x != nil && x.ValidNotAfter != nil {
		return *x.ValidNotAfter
	}
	return 0
}

func (x *SignCertificateRequest) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *SignCertificateRequest) GetCrlDistributionPoints() []string {
	if x != nil {
		return x.CrlDistributionPoints
	}
	return nil
}

func (x *SignCertificateRequest) GetOutputFormat() SignOutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return SignOutputFormat_DER
}

// Response to a SignCertificate Request
type SignCertificateResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to SignedCertificate:
	//
	//	*SignCertificateResponse_Pem
	//	*SignCertificateResponse_Der
	SignedCertificate isSignCertificateResponse_SignedCertificate `protobuf_oneof:"signedCertificate"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignCertificateResponse) Reset() {
	*x = SignCertificateResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCertificateResponse) ProtoMessage() {}

func (x *SignCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCertificateResponse.ProtoReflect.Descriptor instead.
func (*SignCertificateResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SignCertificateResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SignCertificateResponse) GetSignedCertificate() isSignCertificateResponse_SignedCertificate {
	if x != nil {
		return x.SignedCertificate
	}
	return nil
}

func (x *SignCertificateResponse) GetPem() string {
	if x != nil {
		if x, ok := x.SignedCertificate.(*SignCertificateResponse_Pem); ok {
			return x.Pem
		}
	}
	return ""
}

func (x *SignCertificateResponse) GetDer() []byte {
	if x != nil {
		if x, ok := x.SignedCertificate.(*SignCertificateResponse_Der); ok {
			return x.Der
		}
	}
	return nil
}

type isSignCertificateResponse_SignedCertificate interface {
	isSignCertificateResponse_SignedCertificate()
}

type SignCertificateResponse_Pem struct {
	Pem string `protobuf:"bytes,3,opt,name=pem,proto3,oneof"`
}

type SignCertificateResponse_Der struct {
	Der []byte `protobuf:"bytes,4,opt,name=der,proto3,oneof"`
}

func (*SignCertificateResponse_Pem) isSignCertificateResponse_SignedCertificate() {}

func (*SignCertificateResponse_Der) isSignCertificateResponse_SignedCertificate() {}

// Benchmark request and response messages
type BenchmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BenchmarkRequest) Reset() {
	*x = BenchmarkRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkRequest) ProtoMessage() {}

func (x *BenchmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkRequest.ProtoReflect.Descriptor instead.
func (*BenchmarkRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BenchmarkRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BenchmarkResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BenchmarkResults string                 `protobuf:"bytes,1,opt,name=benchmarkResults,proto3" json:"benchmarkResults,omitempty"`
	Metadata         *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BenchmarkResponse) Reset() {
	*x = BenchmarkResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkResponse) ProtoMessage() {}

func (x *BenchmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkResponse.ProtoReflect.Descriptor instead.
func (*BenchmarkResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{7}
}

func (x *BenchmarkResponse) GetBenchmarkResults() string {
	if x != nil {
		return x.BenchmarkResults
	}
	return ""
}

func (x *BenchmarkResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// FakeEndpoint request and response messages
type FakeEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakeEndpointRequest) Reset() {
	*x = FakeEndpointRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeEndpointRequest) ProtoMessage() {}

func (x *FakeEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeEndpointRequest.ProtoReflect.Descriptor instead.
func (*FakeEndpointRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{8}
}

func (x *FakeEndpointRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FakeEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakeEndpointResponse) Reset() {
	*x = FakeEndpointResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeEndpointResponse) ProtoMessage() {}

func (x *FakeEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeEndpointResponse.ProtoReflect.Descriptor instead.
func (*FakeEndpointResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{9}
}

func (x *FakeEndpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FakeEndpointResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_protobuf_messages_proto protoreflect.FileDescriptor

const file_protobuf_messages_proto_rawDesc = "" +
	"\n" +
	"\x17protobuf/messages.proto\x12\fCryptoBroker\"p\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\ftraceContext\x18\x03 \x01(\v2\x1a.CryptoBroker.TraceContextH\x00R\ftraceContext\x88\x01\x01B\x0f\n" +
	"\r_traceContext\"\xa6\x01\n" +
	"\fTraceContext\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x16\n" +
	"\x06spanId\x18\x02 \x01(\tR\x06spanId\x12\x1e\n" +
	"\n" +
	"traceFlags\x18\x03 \x01(\tR\n" +
	"traceFlags\x12\x1e\n" +
	"\n" +
	"traceState\x18\x04 \x01(\tR\n" +
	"traceState\x12$\n" +
	"\rcorrelationId\x18\x05 \x01(\tR\rcorrelationId\"\xb9\x01\n" +
	"\x0fHashDataRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12B\n" +
	"\foutputFormat\x18\x04 \x01(\x0e2\x1e.CryptoBroker.HashOutputFormatR\foutputFormat\"\xc5\x01\n" +
	"\x10HashDataResponse\x12$\n" +
	"\rhashAlgorithm\x18\x02 \x01(\tR\rhashAlgorithm\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12$\n" +
	"\fhashValueHex\x18\x04 \x01(\tH\x00R\fhashValueHex\x12$\n" +
	"\fhashValueRaw\x18\x05 \x01(\fH\x00R\fhashValueRawB\v\n" +
	"\thashValue\"\xd6\x03\n" +
	"\x16SignCertificateRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x10\n" +
	"\x03csr\x18\x02 \x01(\tR\x03csr\x12\"\n" +
	"\fcaPrivateKey\x18\x03 \x01(\tR\fcaPrivateKey\x12\x16\n" +
	"\x06caCert\x18\x04 \x01(\tR\x06caCert\x122\n" +
	"\bmetadata\x18\x05 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12+\n" +
	"\x0evalidNotBefore\x18\x06 \x01(\x04H\x00R\x0evalidNotBefore\x88\x01\x01\x12)\n" +
	"\rvalidNotAfter\x18\a \x01(\x04H\x01R\rvalidNotAfter\x88\x01\x01\x12\x1d\n" +
	"\asubject\x18\b \x01(\tH\x02R\asubject\x88\x01\x01\x124\n" +
	"\x15crlDistributionPoints\x18\t \x03(\tR\x15crlDistributionPoints\x12B\n" +
	"\foutputFormat\x18\n" +
	" \x01(\x0e2\x1e.CryptoBroker.SignOutputFormatR\foutputFormatB\x11\n" +
	"\x0f_validNotBeforeB\x10\n" +
	"\x0e_validNotAfterB\n" +
	"\n" +
	"\b_subject\"\x8a\x01\n" +
	"\x17SignCertificateResponse\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12\x12\n" +
	"\x03pem\x18\x03 \x01(\tH\x00R\x03pem\x12\x12\n" +
	"\x03der\x18\x04 \x01(\fH\x00R\x03derB\x13\n" +
	"\x11signedCertificate\"F\n" +
	"\x10BenchmarkRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"s\n" +
	"\x11BenchmarkResponse\x12*\n" +
	"\x10benchmarkResults\x18\x01 \x01(\tR\x10benchmarkResults\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"I\n" +
	"\x13FakeEndpointRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"d\n" +
	"\x14FakeEndpointResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata*$\n" +
	"\x10HashOutputFormat\x12\a\n" +
	"\x03HEX\x10\x00\x12\a\n" +
	"\x03RAW\x10\x01*$\n" +
	"\x10SignOutputFormat\x12\a\n" +
	"\x03DER\x10\x00\x12\a\n" +
	"\x03PEM\x10\x012\xb7\x01\n" +
	"\n" +
	"CryptoGrpc\x12I\n" +
	"\bHashData\x12\x1d.CryptoBroker.HashDataRequest\x1a\x1e.CryptoBroker.HashDataResponse\x12^\n" +
	"\x0fSignCertificate\x12$.CryptoBroker.SignCertificateRequest\x1a%.CryptoBroker.SignCertificateResponse2\xb4\x01\n" +
	"\rCryptoGrpcDev\x12L\n" +
	"\tBenchmark\x12\x1e.CryptoBroker.BenchmarkRequest\x1a\x1f.CryptoBroker.BenchmarkResponse\x12U\n" +
	"\fFakeEndpoint\x12!.CryptoBroker.FakeEndpointRequest\x1a\".CryptoBroker.FakeEndpointResponseB\x13Z\x11internal/protobufb\x06proto3"

var (
	file_protobuf_messages_proto_rawDescOnce sync.Once
	file_protobuf_messages_proto_rawDescData []byte
)

func file_protobuf_messages_proto_rawDescGZIP() []byte {
	file_protobuf_messages_proto_rawDescOnce.Do(func() {
		file_protobuf_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_messages_proto_rawDesc), len(file_protobuf_messages_proto_rawDesc)))
	})
	return file_protobuf_messages_proto_rawDescData
}

var file_protobuf_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protobuf_messages_proto_goTypes = []any{
	(HashOutputFormat)(0),           // 0: CryptoBroker.HashOutputFormat
	(SignOutputFormat)(0),           // 1: CryptoBroker.SignOutputFormat
	(*Metadata)(nil),                // 2: CryptoBroker.Metadata
	(*TraceContext)(nil),            // 3: CryptoBroker.TraceContext
	(*HashDataRequest)(nil),         // 4: CryptoBroker.HashDataRequest
	(*HashDataResponse)(nil),        // 5: CryptoBroker.HashDataResponse
	(*SignCertificateRequest)(nil),  // 6: CryptoBroker.SignCertificateRequest
	(*SignCertificateResponse)(nil), // 7: CryptoBroker.SignCertificateResponse
	(*BenchmarkRequest)(nil),        // 8: CryptoBroker.BenchmarkRequest
	(*BenchmarkResponse)(nil),       // 9: CryptoBroker.BenchmarkResponse
	(*FakeEndpointRequest)(nil),     // 10: CryptoBroker.FakeEndpointRequest
	(*FakeEndpointResponse)(nil),    // 11: CryptoBroker.FakeEndpointResponse
}
var file_protobuf_messages_proto_depIdxs = []int32{
	3,  // 0: CryptoBroker.Metadata.traceContext:type_name -> CryptoBroker.TraceContext
	2,  // 1: CryptoBroker.HashDataRequest.metadata:type_name -> CryptoBroker.Metadata
	0,  // 2: CryptoBroker.HashDataRequest.outputFormat:type_name -> CryptoBroker.HashOutputFormat
	2,  // 3: CryptoBroker.HashDataResponse.metadata:type_name -> CryptoBroker.Metadata
	2,  // 4: CryptoBroker.SignCertificateRequest.metadata:type_name -> CryptoBroker.Metadata
	1,  // 5: CryptoBroker.SignCertificateRequest.outputFormat:type_name -> CryptoBroker.SignOutputFormat
	2,  // 6: CryptoBroker.SignCertificateResponse.metadata:type_name -> CryptoBroker.Metadata
	2,  // 7: CryptoBroker.BenchmarkRequest.metadata:type_name -> CryptoBroker.Metadata
	2,  // 8: CryptoBroker.BenchmarkResponse.metadata:type_name -> CryptoBroker.Metadata
	2,  // 9: CryptoBroker.FakeEndpointRequest.metadata:type_name -> CryptoBroker.Metadata
	2,  // 10: CryptoBroker.FakeEndpointResponse.metadata:type_name -> CryptoBroker.Metadata
	4,  // 11: CryptoBroker.CryptoGrpc.HashData:input_type -> CryptoBroker.HashDataRequest
	6,  // 12: CryptoBroker.CryptoGrpc.SignCertificate:input_type -> CryptoBroker.SignCertificateRequest
	8,  // 13: CryptoBroker.CryptoGrpcDev.Benchmark:input_type -> CryptoBroker.BenchmarkRequest
	10, // 14: CryptoBroker.CryptoGrpcDev.FakeEndpoint:input_type -> CryptoBroker.FakeEndpointRequest
	5,  // 15: CryptoBroker.CryptoGrpc.HashData:output_type -> CryptoBroker.HashDataResponse
	7,  // 16: CryptoBroker.CryptoGrpc.SignCertificate:output_type -> CryptoBroker.SignCertificateResponse
	9,  // 17: CryptoBroker.CryptoGrpcDev.Benchmark:output_type -> CryptoBroker.BenchmarkResponse
	11, // 18: CryptoBroker.CryptoGrpcDev.FakeEndpoint:output_type -> CryptoBroker.FakeEndpointResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protobuf_messages_proto_init() }
func file_protobuf_messages_proto_init() {
	if File_protobuf_messages_proto != nil {
		return
	}
	file_protobuf_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*HashDataResponse_HashValueHex)(nil),
		(*HashDataResponse_HashValueRaw)(nil),
	}
	file_protobuf_messages_proto_msgTypes[4].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[5].OneofWrappers = []any{
		(*SignCertificateResponse_Pem)(nil),
		(*SignCertificateResponse_Der)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_messages_proto_rawDesc), len(file_protobuf_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobuf_messages_proto_goTypes,
		DependencyIndexes: file_protobuf_messages_proto_depIdxs,
		EnumInfos:         file_protobuf_messages_proto_enumTypes,
		MessageInfos:      file_protobuf_messages_proto_msgTypes,
	}.Build()
	File_protobuf_messages_proto = out.File
	file_protobuf_messages_proto_goTypes = nil
	file_protobuf_messages_proto_depIdxs = nil
}
