// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: protobuf/messages.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptoBroker_Hash_FullMethodName = "/protobuf.CryptoBroker/Hash"
	CryptoBroker_Sign_FullMethodName = "/protobuf.CryptoBroker/Sign"
)

// CryptoBrokerClient is the client API for CryptoBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoBrokerClient interface {
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type cryptoBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoBrokerClient(cc grpc.ClientConnInterface) CryptoBrokerClient {
	return &cryptoBrokerClient{cc}
}

func (c *cryptoBrokerClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, CryptoBroker_Hash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoBrokerClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, CryptoBroker_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoBrokerServer is the server API for CryptoBroker service.
// All implementations must embed UnimplementedCryptoBrokerServer
// for forward compatibility.
type CryptoBrokerServer interface {
	Hash(context.Context, *HashRequest) (*HashResponse, error)
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	mustEmbedUnimplementedCryptoBrokerServer()
}

// UnimplementedCryptoBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoBrokerServer struct{}

func (UnimplementedCryptoBrokerServer) Hash(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hash not implemented")
}
func (UnimplementedCryptoBrokerServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedCryptoBrokerServer) mustEmbedUnimplementedCryptoBrokerServer() {}
func (UnimplementedCryptoBrokerServer) testEmbeddedByValue()                      {}

// UnsafeCryptoBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoBrokerServer will
// result in compilation errors.
type UnsafeCryptoBrokerServer interface {
	mustEmbedUnimplementedCryptoBrokerServer()
}

func RegisterCryptoBrokerServer(s grpc.ServiceRegistrar, srv CryptoBrokerServer) {
	// If the following call pancis, it indicates UnimplementedCryptoBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptoBroker_ServiceDesc, srv)
}

func _CryptoBroker_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoBrokerServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoBroker_Hash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoBrokerServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoBroker_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoBrokerServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoBroker_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoBrokerServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoBroker_ServiceDesc is the grpc.ServiceDesc for CryptoBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.CryptoBroker",
	HandlerType: (*CryptoBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hash",
			Handler:    _CryptoBroker_Hash_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _CryptoBroker_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/messages.proto",
}
