// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protobuf/messages.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Output formats
type HashOutputFormat int32

const (
	HashOutputFormat_HEX HashOutputFormat = 0
	HashOutputFormat_RAW HashOutputFormat = 1
)

// Enum value maps for HashOutputFormat.
var (
	HashOutputFormat_name = map[int32]string{
		0: "HEX",
		1: "RAW",
	}
	HashOutputFormat_value = map[string]int32{
		"HEX": 0,
		"RAW": 1,
	}
)

func (x HashOutputFormat) Enum() *HashOutputFormat {
	p := new(HashOutputFormat)
	*p = x
	return p
}

func (x HashOutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashOutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_messages_proto_enumTypes[0].Descriptor()
}

func (HashOutputFormat) Type() protoreflect.EnumType {
	return &file_protobuf_messages_proto_enumTypes[0]
}

func (x HashOutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashOutputFormat.Descriptor instead.
func (HashOutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{0}
}

type SignOutputFormat int32

const (
	SignOutputFormat_DER SignOutputFormat = 0
	SignOutputFormat_PEM SignOutputFormat = 1
)

// Enum value maps for SignOutputFormat.
var (
	SignOutputFormat_name = map[int32]string{
		0: "DER",
		1: "PEM",
	}
	SignOutputFormat_value = map[string]int32{
		"DER": 0,
		"PEM": 1,
	}
)

func (x SignOutputFormat) Enum() *SignOutputFormat {
	p := new(SignOutputFormat)
	*p = x
	return p
}

func (x SignOutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignOutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_messages_proto_enumTypes[1].Descriptor()
}

func (SignOutputFormat) Type() protoreflect.EnumType {
	return &file_protobuf_messages_proto_enumTypes[1]
}

func (x SignOutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignOutputFormat.Descriptor instead.
func (SignOutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{1}
}

// Output format for signatures produced by SignData and accepted by VerifyData.
// SIGNATURE_CMS wraps the signature in an RFC 5652 CMS SignedData structure;
// the other formats carry the bare signature value in the requested encoding.
type SignatureFormat int32

const (
	SignatureFormat_SIGNATURE_RAW SignatureFormat = 0
	SignatureFormat_SIGNATURE_DER SignatureFormat = 1
	SignatureFormat_SIGNATURE_PEM SignatureFormat = 2
	SignatureFormat_SIGNATURE_CMS SignatureFormat = 3
)

// Enum value maps for SignatureFormat.
var (
	SignatureFormat_name = map[int32]string{
		0: "SIGNATURE_RAW",
		1: "SIGNATURE_DER",
		2: "SIGNATURE_PEM",
		3: "SIGNATURE_CMS",
	}
	SignatureFormat_value = map[string]int32{
		"SIGNATURE_RAW": 0,
		"SIGNATURE_DER": 1,
		"SIGNATURE_PEM": 2,
		"SIGNATURE_CMS": 3,
	}
)

func (x SignatureFormat) Enum() *SignatureFormat {
	p := new(SignatureFormat)
	*p = x
	return p
}

func (x SignatureFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_messages_proto_enumTypes[2].Descriptor()
}

func (SignatureFormat) Type() protoreflect.EnumType {
	return &file_protobuf_messages_proto_enumTypes[2]
}

func (x SignatureFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureFormat.Descriptor instead.
func (SignatureFormat) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{2}
}

// Single source of truth for gRPC message size limits, applied as transport options in the server and clients.
type MessageSizeLimit int32

const (
	MessageSizeLimit_MESSAGE_SIZE_LIMIT_UNSPECIFIED MessageSizeLimit = 0
	// Max request accepted from client to server (2 MiB).
	MessageSizeLimit_MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES MessageSizeLimit = 2097152
	// Max response returned from server to client (1 MiB).
	MessageSizeLimit_MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES MessageSizeLimit = 1048576
)

// Enum value maps for MessageSizeLimit.
var (
	MessageSizeLimit_name = map[int32]string{
		0:       "MESSAGE_SIZE_LIMIT_UNSPECIFIED",
		2097152: "MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES",
		1048576: "MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES",
	}
	MessageSizeLimit_value = map[string]int32{
		"MESSAGE_SIZE_LIMIT_UNSPECIFIED":        0,
		"MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES":  2097152,
		"MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES": 1048576,
	}
)

func (x MessageSizeLimit) Enum() *MessageSizeLimit {
	p := new(MessageSizeLimit)
	*p = x
	return p
}

func (x MessageSizeLimit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageSizeLimit) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_messages_proto_enumTypes[3].Descriptor()
}

func (MessageSizeLimit) Type() protoreflect.EnumType {
	return &file_protobuf_messages_proto_enumTypes[3]
}

func (x MessageSizeLimit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageSizeLimit.Descriptor instead.
func (MessageSizeLimit) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{3}
}

// Single source of truth for payload field size limits (values in bytes)
type PayloadLimits int32

const (
	PayloadLimits_PAYLOAD_LIMITS_UNSPECIFIED PayloadLimits = 0
	// Profile and Metadata
	PayloadLimits_PAYLOAD_LIMITS_PROFILE_MAX_LEN     PayloadLimits = 64
	PayloadLimits_PAYLOAD_LIMITS_METADATA_ID_MAX_LEN PayloadLimits = 128
	// Hash Data
	PayloadLimits_PAYLOAD_LIMITS_HASH_DATA_INPUT_MAX_LEN PayloadLimits = 1048576 // 1 MiB
	// Sign Certificate
	PayloadLimits_PAYLOAD_LIMITS_SIGN_CERTIFICATE_CSR_MAX_LEN                PayloadLimits = 65536 // 64 KiB
	PayloadLimits_PAYLOAD_LIMITS_SIGN_CERTIFICATE_CA_PRIVATE_KEY_MAX_LEN     PayloadLimits = 65536 // 64 KiB
	PayloadLimits_PAYLOAD_LIMITS_SIGN_CERTIFICATE_CA_CERT_MAX_LEN            PayloadLimits = 65536 // 64 KiB
	PayloadLimits_PAYLOAD_LIMITS_SIGN_CERTIFICATE_SUBJECT_MAX_LEN            PayloadLimits = 1024  // 1 KiB
	PayloadLimits_PAYLOAD_LIMITS_SIGN_CERTIFICATE_DISTRIBUTION_POINTS_MAX    PayloadLimits = 16    // #Entries, not bytes
	PayloadLimits_PAYLOAD_LIMITS_SIGN_CERTIFICATE_DISTRIBUTION_POINT_MAX_LEN PayloadLimits = 2048  // 2 KiB
	// Encrypt / Decrypt Data
	PayloadLimits_PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_KEYSOURCE_KEY_ID_MAX_LEN  PayloadLimits = 64
	PayloadLimits_PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_KEYSOURCE_KEY_RAW_MAX_LEN PayloadLimits = 32
	PayloadLimits_PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_DATA_MAX_LEN              PayloadLimits = 64
	PayloadLimits_PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_NONCE_MAX_LEN             PayloadLimits = 32
	PayloadLimits_PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_TAG_MAX_LEN               PayloadLimits = 32
	PayloadLimits_PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_AAD_MAX_LEN               PayloadLimits = 32
	// Sign / Verify Data
	// TBD
	// Tracing
	PayloadLimits_PAYLOAD_LIMITS_TRACE_ID_MAX_LEN             PayloadLimits = 32
	PayloadLimits_PAYLOAD_LIMITS_TRACE_SPAN_ID_MAX_LEN        PayloadLimits = 16
	PayloadLimits_PAYLOAD_LIMITS_TRACE_FLAGS_MAX_LEN          PayloadLimits = 2
	PayloadLimits_PAYLOAD_LIMITS_TRACE_STATE_MAX_LEN          PayloadLimits = 512
	PayloadLimits_PAYLOAD_LIMITS_TRACE_CORRELATION_ID_MAX_LEN PayloadLimits = 128
)

// Enum value maps for PayloadLimits.
var (
	PayloadLimits_name = map[int32]string{
		0:       "PAYLOAD_LIMITS_UNSPECIFIED",
		64:      "PAYLOAD_LIMITS_PROFILE_MAX_LEN",
		128:     "PAYLOAD_LIMITS_METADATA_ID_MAX_LEN",
		1048576: "PAYLOAD_LIMITS_HASH_DATA_INPUT_MAX_LEN",
		65536:   "PAYLOAD_LIMITS_SIGN_CERTIFICATE_CSR_MAX_LEN",
		// Duplicate value: 65536: "PAYLOAD_LIMITS_SIGN_CERTIFICATE_CA_PRIVATE_KEY_MAX_LEN",
		// Duplicate value: 65536: "PAYLOAD_LIMITS_SIGN_CERTIFICATE_CA_CERT_MAX_LEN",
		1024: "PAYLOAD_LIMITS_SIGN_CERTIFICATE_SUBJECT_MAX_LEN",
		16:   "PAYLOAD_LIMITS_SIGN_CERTIFICATE_DISTRIBUTION_POINTS_MAX",
		2048: "PAYLOAD_LIMITS_SIGN_CERTIFICATE_DISTRIBUTION_POINT_MAX_LEN",
		// Duplicate value: 64: "PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_KEYSOURCE_KEY_ID_MAX_LEN",
		32: "PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_KEYSOURCE_KEY_RAW_MAX_LEN",
		// Duplicate value: 64: "PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_DATA_MAX_LEN",
		// Duplicate value: 32: "PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_NONCE_MAX_LEN",
		// Duplicate value: 32: "PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_TAG_MAX_LEN",
		// Duplicate value: 32: "PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_AAD_MAX_LEN",
		// Duplicate value: 32: "PAYLOAD_LIMITS_TRACE_ID_MAX_LEN",
		// Duplicate value: 16: "PAYLOAD_LIMITS_TRACE_SPAN_ID_MAX_LEN",
		2:   "PAYLOAD_LIMITS_TRACE_FLAGS_MAX_LEN",
		512: "PAYLOAD_LIMITS_TRACE_STATE_MAX_LEN",
		// Duplicate value: 128: "PAYLOAD_LIMITS_TRACE_CORRELATION_ID_MAX_LEN",
	}
	PayloadLimits_value = map[string]int32{
		"PAYLOAD_LIMITS_UNSPECIFIED":                                    0,
		"PAYLOAD_LIMITS_PROFILE_MAX_LEN":                                64,
		"PAYLOAD_LIMITS_METADATA_ID_MAX_LEN":                            128,
		"PAYLOAD_LIMITS_HASH_DATA_INPUT_MAX_LEN":                        1048576,
		"PAYLOAD_LIMITS_SIGN_CERTIFICATE_CSR_MAX_LEN":                   65536,
		"PAYLOAD_LIMITS_SIGN_CERTIFICATE_CA_PRIVATE_KEY_MAX_LEN":        65536,
		"PAYLOAD_LIMITS_SIGN_CERTIFICATE_CA_CERT_MAX_LEN":               65536,
		"PAYLOAD_LIMITS_SIGN_CERTIFICATE_SUBJECT_MAX_LEN":               1024,
		"PAYLOAD_LIMITS_SIGN_CERTIFICATE_DISTRIBUTION_POINTS_MAX":       16,
		"PAYLOAD_LIMITS_SIGN_CERTIFICATE_DISTRIBUTION_POINT_MAX_LEN":    2048,
		"PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_KEYSOURCE_KEY_ID_MAX_LEN":  64,
		"PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_KEYSOURCE_KEY_RAW_MAX_LEN": 32,
		"PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_DATA_MAX_LEN":              64,
		"PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_NONCE_MAX_LEN":             32,
		"PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_TAG_MAX_LEN":               32,
		"PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_AAD_MAX_LEN":               32,
		"PAYLOAD_LIMITS_TRACE_ID_MAX_LEN":                               32,
		"PAYLOAD_LIMITS_TRACE_SPAN_ID_MAX_LEN":                          16,
		"PAYLOAD_LIMITS_TRACE_FLAGS_MAX_LEN":                            2,
		"PAYLOAD_LIMITS_TRACE_STATE_MAX_LEN":                            512,
		"PAYLOAD_LIMITS_TRACE_CORRELATION_ID_MAX_LEN":                   128,
	}
)

func (x PayloadLimits) Enum() *PayloadLimits {
	p := new(PayloadLimits)
	*p = x
	return p
}

func (x PayloadLimits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadLimits) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_messages_proto_enumTypes[4].Descriptor()
}

func (PayloadLimits) Type() protoreflect.EnumType {
	return &file_protobuf_messages_proto_enumTypes[4]
}

func (x PayloadLimits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadLimits.Descriptor instead.
func (PayloadLimits) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{4}
}

// Meta-structures shared across other messages and functions
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Attached to every response produced with a deprecated profile (see ADR 0013).
	Deprecation   *DeprecationWarning `protobuf:"bytes,2,opt,name=deprecation,proto3,oneof" json:"deprecation,omitempty"`
	TraceContext  *TraceContext       `protobuf:"bytes,3,opt,name=traceContext,proto3,oneof" json:"traceContext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_protobuf_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetDeprecation() *DeprecationWarning {
	if x != nil {
		return x.Deprecation
	}
	return nil
}

func (x *Metadata) GetTraceContext() *TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

// Self-describing record of how a stored artifact was produced (see ADR 0013).
// Persisted by the caller alongside the value so it stays verifiable and
// migratable without access to Profiles.yaml.
type CryptoDescriptor struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Profile string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// The API that produced the artifact, e.g. "HashData", "SignCertificate", "EncryptData".
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// The concrete algorithm actually used, e.g. "sha3-512", "aes-gcm".
	Algorithm     string `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoDescriptor) Reset() {
	*x = CryptoDescriptor{}
	mi := &file_protobuf_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoDescriptor) ProtoMessage() {}

func (x *CryptoDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoDescriptor.ProtoReflect.Descriptor instead.
func (*CryptoDescriptor) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CryptoDescriptor) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *CryptoDescriptor) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CryptoDescriptor) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// Deprecation signal for a profile scheduled for a rolling migration (see ADR 0013).
// replacedBy should point to an equal-or-stronger profile.
type DeprecationWarning struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Profile         string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	ReplacedBy      *string                `protobuf:"bytes,2,opt,name=replacedBy,proto3,oneof" json:"replacedBy,omitempty"`
	DeprecatedSince *string                `protobuf:"bytes,3,opt,name=deprecatedSince,proto3,oneof" json:"deprecatedSince,omitempty"`
	RemoveAfter     *string                `protobuf:"bytes,4,opt,name=removeAfter,proto3,oneof" json:"removeAfter,omitempty"`
	Reason          *string                `protobuf:"bytes,5,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeprecationWarning) Reset() {
	*x = DeprecationWarning{}
	mi := &file_protobuf_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecationWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecationWarning) ProtoMessage() {}

func (x *DeprecationWarning) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecationWarning.ProtoReflect.Descriptor instead.
func (*DeprecationWarning) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DeprecationWarning) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *DeprecationWarning) GetReplacedBy() string {
	if x != nil && x.ReplacedBy != nil {
		return *x.ReplacedBy
	}
	return ""
}

func (x *DeprecationWarning) GetDeprecatedSince() string {
	if x != nil && x.DeprecatedSince != nil {
		return *x.DeprecatedSince
	}
	return ""
}

func (x *DeprecationWarning) GetRemoveAfter() string {
	if x != nil && x.RemoveAfter != nil {
		return *x.RemoveAfter
	}
	return ""
}

func (x *DeprecationWarning) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// Trace context for manual propagation
type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=spanId,proto3" json:"spanId,omitempty"`
	TraceFlags    string                 `protobuf:"bytes,3,opt,name=traceFlags,proto3" json:"traceFlags,omitempty"`
	TraceState    string                 `protobuf:"bytes,4,opt,name=traceState,proto3" json:"traceState,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_protobuf_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TraceContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceContext) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *TraceContext) GetTraceFlags() string {
	if x != nil {
		return x.TraceFlags
	}
	return ""
}

func (x *TraceContext) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

func (x *TraceContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Key material source for symmetric encryption/decryption.
// Exactly one variant is set, governed by the profile:
// rawKey for caller-managed profiles (no KMS), keyId for KMS profiles where the broker
// resolves the identifier and retrieves the externally provisioned key. The broker never
// creates, imports, or deletes keys; key lifecycle is owned by the KMS/operator.
type KeySource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*KeySource_KeyId
	//	*KeySource_RawKey
	Source        isKeySource_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySource) Reset() {
	*x = KeySource{}
	mi := &file_protobuf_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySource) ProtoMessage() {}

func (x *KeySource) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySource.ProtoReflect.Descriptor instead.
func (*KeySource) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{4}
}

func (x *KeySource) GetSource() isKeySource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *KeySource) GetKeyId() string {
	if x != nil {
		if x, ok := x.Source.(*KeySource_KeyId); ok {
			return x.KeyId
		}
	}
	return ""
}

func (x *KeySource) GetRawKey() []byte {
	if x != nil {
		if x, ok := x.Source.(*KeySource_RawKey); ok {
			return x.RawKey
		}
	}
	return nil
}

type isKeySource_Source interface {
	isKeySource_Source()
}

type KeySource_KeyId struct {
	KeyId string `protobuf:"bytes,1,opt,name=keyId,proto3,oneof"`
}

type KeySource_RawKey struct {
	RawKey []byte `protobuf:"bytes,2,opt,name=rawKey,proto3,oneof"`
}

func (*KeySource_KeyId) isKeySource_Source() {}

func (*KeySource_RawKey) isKeySource_Source() {}

// Signing key material for SignData/VerifyData.
// Legacy and post-quantum modes use a single KeySource. Hybrid (composite)
// mode uses two component keys via componentKeys: the traditional key and the
// ML-DSA key. For VerifyData the KeySource(s) carry the corresponding public keys.
type SignKeySource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*SignKeySource_Single
	//	*SignKeySource_ComponentKeys
	Source        isSignKeySource_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignKeySource) Reset() {
	*x = SignKeySource{}
	mi := &file_protobuf_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignKeySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignKeySource) ProtoMessage() {}

func (x *SignKeySource) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignKeySource.ProtoReflect.Descriptor instead.
func (*SignKeySource) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SignKeySource) GetSource() isSignKeySource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SignKeySource) GetSingle() *KeySource {
	if x != nil {
		if x, ok := x.Source.(*SignKeySource_Single); ok {
			return x.Single
		}
	}
	return nil
}

func (x *SignKeySource) GetComponentKeys() *ComponentKeys {
	if x != nil {
		if x, ok := x.Source.(*SignKeySource_ComponentKeys); ok {
			return x.ComponentKeys
		}
	}
	return nil
}

type isSignKeySource_Source interface {
	isSignKeySource_Source()
}

type SignKeySource_Single struct {
	Single *KeySource `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type SignKeySource_ComponentKeys struct {
	ComponentKeys *ComponentKeys `protobuf:"bytes,2,opt,name=componentKeys,proto3,oneof"`
}

func (*SignKeySource_Single) isSignKeySource_Source() {}

func (*SignKeySource_ComponentKeys) isSignKeySource_Source() {}

// Ordered list of component key sources for hybrid (composite) signing:
// the traditional key followed by the ML-DSA key.
type ComponentKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeySource           `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentKeys) Reset() {
	*x = ComponentKeys{}
	mi := &file_protobuf_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentKeys) ProtoMessage() {}

func (x *ComponentKeys) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentKeys.ProtoReflect.Descriptor instead.
func (*ComponentKeys) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ComponentKeys) GetKeys() []*KeySource {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Caller-supplied encryption parameters. The nonce is always provided by the caller;
// neither the broker nor the KMS generates it, so the caller owns nonce-uniqueness. AAD is optional.
type EncryptMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Aad           []byte                 `protobuf:"bytes,2,opt,name=aad,proto3,oneof" json:"aad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptMetadata) Reset() {
	*x = EncryptMetadata{}
	mi := &file_protobuf_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptMetadata) ProtoMessage() {}

func (x *EncryptMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptMetadata.ProtoReflect.Descriptor instead.
func (*EncryptMetadata) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{7}
}

func (x *EncryptMetadata) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptMetadata) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

// Metadata returned alongside the ciphertext by EncryptData. It encapsulates
// everything the caller may need besides the ciphertext itself:
//   - keyId: echoed for KMS profiles; key material is never returned.
//   - nonce/aad: echoed back; the caller supplied them and must retain them to decrypt.
//   - tag: the authentication tag the caller must retain to decrypt later.
type CipherMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         *string                `protobuf:"bytes,1,opt,name=keyId,proto3,oneof" json:"keyId,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Aad           []byte                 `protobuf:"bytes,3,opt,name=aad,proto3,oneof" json:"aad,omitempty"`
	Tag           []byte                 `protobuf:"bytes,4,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CipherMetadata) Reset() {
	*x = CipherMetadata{}
	mi := &file_protobuf_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CipherMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CipherMetadata) ProtoMessage() {}

func (x *CipherMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CipherMetadata.ProtoReflect.Descriptor instead.
func (*CipherMetadata) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{8}
}

func (x *CipherMetadata) GetKeyId() string {
	if x != nil && x.KeyId != nil {
		return *x.KeyId
	}
	return ""
}

func (x *CipherMetadata) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *CipherMetadata) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

func (x *CipherMetadata) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

// Caller-supplied parameters for DecryptData. Symmetric to EncryptMetadata.
// The caller provides the nonce, AAD and tag, typically by echoing back the
// values from the CipherMetadata receipt returned by EncryptData.
type DecryptMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Aad           []byte                 `protobuf:"bytes,2,opt,name=aad,proto3,oneof" json:"aad,omitempty"`
	Tag           []byte                 `protobuf:"bytes,3,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptMetadata) Reset() {
	*x = DecryptMetadata{}
	mi := &file_protobuf_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptMetadata) ProtoMessage() {}

func (x *DecryptMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptMetadata.ProtoReflect.Descriptor instead.
func (*DecryptMetadata) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DecryptMetadata) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *DecryptMetadata) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

func (x *DecryptMetadata) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

// HashData request and response messages
type HashDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OutputFormat  HashOutputFormat       `protobuf:"varint,4,opt,name=outputFormat,proto3,enum=CryptoBroker.HashOutputFormat" json:"outputFormat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashDataRequest) Reset() {
	*x = HashDataRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashDataRequest) ProtoMessage() {}

func (x *HashDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashDataRequest.ProtoReflect.Descriptor instead.
func (*HashDataRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{10}
}

func (x *HashDataRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *HashDataRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *HashDataRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HashDataRequest) GetOutputFormat() HashOutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return HashOutputFormat_HEX
}

type HashDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redundant with descriptor.algorithm; retained for backward compatibility.
	HashAlgorithm string    `protobuf:"bytes,2,opt,name=hashAlgorithm,proto3" json:"hashAlgorithm,omitempty"`
	Metadata      *Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to HashValue:
	//
	//	*HashDataResponse_HashValueHex
	//	*HashDataResponse_HashValueRaw
	HashValue     isHashDataResponse_HashValue `protobuf_oneof:"hashValue"`
	Descriptor_   *CryptoDescriptor            `protobuf:"bytes,6,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashDataResponse) Reset() {
	*x = HashDataResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashDataResponse) ProtoMessage() {}

func (x *HashDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashDataResponse.ProtoReflect.Descriptor instead.
func (*HashDataResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{11}
}

func (x *HashDataResponse) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

func (x *HashDataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HashDataResponse) GetHashValue() isHashDataResponse_HashValue {
	if x != nil {
		return x.HashValue
	}
	return nil
}

func (x *HashDataResponse) GetHashValueHex() string {
	if x != nil {
		if x, ok := x.HashValue.(*HashDataResponse_HashValueHex); ok {
			return x.HashValueHex
		}
	}
	return ""
}

func (x *HashDataResponse) GetHashValueRaw() []byte {
	if x != nil {
		if x, ok := x.HashValue.(*HashDataResponse_HashValueRaw); ok {
			return x.HashValueRaw
		}
	}
	return nil
}

func (x *HashDataResponse) GetDescriptor_() *CryptoDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

type isHashDataResponse_HashValue interface {
	isHashDataResponse_HashValue()
}

type HashDataResponse_HashValueHex struct {
	HashValueHex string `protobuf:"bytes,4,opt,name=hashValueHex,proto3,oneof"`
}

type HashDataResponse_HashValueRaw struct {
	HashValueRaw []byte `protobuf:"bytes,5,opt,name=hashValueRaw,proto3,oneof"`
}

func (*HashDataResponse_HashValueHex) isHashDataResponse_HashValue() {}

func (*HashDataResponse_HashValueRaw) isHashDataResponse_HashValue() {}

// SignCertificate response and request messages
type SignCertificateRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Profile               string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Csr                   string                 `protobuf:"bytes,2,opt,name=csr,proto3" json:"csr,omitempty"`
	CaPrivateKey          string                 `protobuf:"bytes,3,opt,name=caPrivateKey,proto3" json:"caPrivateKey,omitempty"`
	CaCert                string                 `protobuf:"bytes,4,opt,name=caCert,proto3" json:"caCert,omitempty"`
	Metadata              *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ValidNotBefore        *uint64                `protobuf:"varint,6,opt,name=validNotBefore,proto3,oneof" json:"validNotBefore,omitempty"`
	ValidNotAfter         *uint64                `protobuf:"varint,7,opt,name=validNotAfter,proto3,oneof" json:"validNotAfter,omitempty"`
	Subject               *string                `protobuf:"bytes,8,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	CrlDistributionPoints []string               `protobuf:"bytes,9,rep,name=crlDistributionPoints,proto3" json:"crlDistributionPoints,omitempty"`
	OutputFormat          SignOutputFormat       `protobuf:"varint,10,opt,name=outputFormat,proto3,enum=CryptoBroker.SignOutputFormat" json:"outputFormat,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SignCertificateRequest) Reset() {
	*x = SignCertificateRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCertificateRequest) ProtoMessage() {}

func (x *SignCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCertificateRequest.ProtoReflect.Descriptor instead.
func (*SignCertificateRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{12}
}

func (x *SignCertificateRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SignCertificateRequest) GetCsr() string {
	if x != nil {
		return x.Csr
	}
	return ""
}

func (x *SignCertificateRequest) GetCaPrivateKey() string {
	if x != nil {
		return x.CaPrivateKey
	}
	return ""
}

func (x *SignCertificateRequest) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *SignCertificateRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SignCertificateRequest) GetValidNotBefore() uint64 {
	if x != nil && x.ValidNotBefore != nil {
		return *x.ValidNotBefore
	}
	return 0
}

func (x *SignCertificateRequest) GetValidNotAfter() uint64 {
	if x != nil && x.ValidNotAfter != nil {
		return *x.ValidNotAfter
	}
	return 0
}

func (x *SignCertificateRequest) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *SignCertificateRequest) GetCrlDistributionPoints() []string {
	if x != nil {
		return x.CrlDistributionPoints
	}
	return nil
}

func (x *SignCertificateRequest) GetOutputFormat() SignOutputFormat {
	if x != nil {
		return x.OutputFormat
	}
	return SignOutputFormat_DER
}

// Response to a SignCertificate Request
type SignCertificateResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to SignedCertificate:
	//
	//	*SignCertificateResponse_Pem
	//	*SignCertificateResponse_Der
	SignedCertificate isSignCertificateResponse_SignedCertificate `protobuf_oneof:"signedCertificate"`
	Descriptor_       *CryptoDescriptor                           `protobuf:"bytes,5,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignCertificateResponse) Reset() {
	*x = SignCertificateResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCertificateResponse) ProtoMessage() {}

func (x *SignCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCertificateResponse.ProtoReflect.Descriptor instead.
func (*SignCertificateResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{13}
}

func (x *SignCertificateResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SignCertificateResponse) GetSignedCertificate() isSignCertificateResponse_SignedCertificate {
	if x != nil {
		return x.SignedCertificate
	}
	return nil
}

func (x *SignCertificateResponse) GetPem() string {
	if x != nil {
		if x, ok := x.SignedCertificate.(*SignCertificateResponse_Pem); ok {
			return x.Pem
		}
	}
	return ""
}

func (x *SignCertificateResponse) GetDer() []byte {
	if x != nil {
		if x, ok := x.SignedCertificate.(*SignCertificateResponse_Der); ok {
			return x.Der
		}
	}
	return nil
}

func (x *SignCertificateResponse) GetDescriptor_() *CryptoDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

type isSignCertificateResponse_SignedCertificate interface {
	isSignCertificateResponse_SignedCertificate()
}

type SignCertificateResponse_Pem struct {
	Pem string `protobuf:"bytes,3,opt,name=pem,proto3,oneof"`
}

type SignCertificateResponse_Der struct {
	Der []byte `protobuf:"bytes,4,opt,name=der,proto3,oneof"`
}

func (*SignCertificateResponse_Pem) isSignCertificateResponse_SignedCertificate() {}

func (*SignCertificateResponse_Der) isSignCertificateResponse_SignedCertificate() {}

// SignData request and response messages
type SignDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Profile         string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	KeySource       *SignKeySource         `protobuf:"bytes,2,opt,name=keySource,proto3" json:"keySource,omitempty"`
	Input           []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	SignatureFormat *SignatureFormat       `protobuf:"varint,4,opt,name=signatureFormat,proto3,enum=CryptoBroker.SignatureFormat,oneof" json:"signatureFormat,omitempty"`
	Metadata        *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignDataRequest) Reset() {
	*x = SignDataRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDataRequest) ProtoMessage() {}

func (x *SignDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDataRequest.ProtoReflect.Descriptor instead.
func (*SignDataRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SignDataRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SignDataRequest) GetKeySource() *SignKeySource {
	if x != nil {
		return x.KeySource
	}
	return nil
}

func (x *SignDataRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *SignDataRequest) GetSignatureFormat() SignatureFormat {
	if x != nil && x.SignatureFormat != nil {
		return *x.SignatureFormat
	}
	return SignatureFormat_SIGNATURE_RAW
}

func (x *SignDataRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SignDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Descriptor_   *CryptoDescriptor      `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignDataResponse) Reset() {
	*x = SignDataResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDataResponse) ProtoMessage() {}

func (x *SignDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDataResponse.ProtoReflect.Descriptor instead.
func (*SignDataResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{15}
}

func (x *SignDataResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignDataResponse) GetDescriptor_() *CryptoDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *SignDataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// VerifyData request and response messages
type VerifyDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Profile         string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	KeySource       *SignKeySource         `protobuf:"bytes,2,opt,name=keySource,proto3" json:"keySource,omitempty"`
	Input           []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Signature       []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureFormat *SignatureFormat       `protobuf:"varint,5,opt,name=signatureFormat,proto3,enum=CryptoBroker.SignatureFormat,oneof" json:"signatureFormat,omitempty"`
	Metadata        *Metadata              `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyDataRequest) Reset() {
	*x = VerifyDataRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDataRequest) ProtoMessage() {}

func (x *VerifyDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDataRequest.ProtoReflect.Descriptor instead.
func (*VerifyDataRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyDataRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *VerifyDataRequest) GetKeySource() *SignKeySource {
	if x != nil {
		return x.KeySource
	}
	return nil
}

func (x *VerifyDataRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *VerifyDataRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VerifyDataRequest) GetSignatureFormat() SignatureFormat {
	if x != nil && x.SignatureFormat != nil {
		return *x.SignatureFormat
	}
	return SignatureFormat_SIGNATURE_RAW
}

func (x *VerifyDataRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type VerifyDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyDataResponse) Reset() {
	*x = VerifyDataResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDataResponse) ProtoMessage() {}

func (x *VerifyDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDataResponse.ProtoReflect.Descriptor instead.
func (*VerifyDataResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyDataResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyDataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// EncryptData request and response messages
type EncryptDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Profile         string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	KeySource       *KeySource             `protobuf:"bytes,2,opt,name=keySource,proto3" json:"keySource,omitempty"`
	Plaintext       []byte                 `protobuf:"bytes,3,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	EncryptMetadata *EncryptMetadata       `protobuf:"bytes,4,opt,name=encryptMetadata,proto3" json:"encryptMetadata,omitempty"`
	Metadata        *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EncryptDataRequest) Reset() {
	*x = EncryptDataRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptDataRequest) ProtoMessage() {}

func (x *EncryptDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptDataRequest.ProtoReflect.Descriptor instead.
func (*EncryptDataRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{18}
}

func (x *EncryptDataRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *EncryptDataRequest) GetKeySource() *KeySource {
	if x != nil {
		return x.KeySource
	}
	return nil
}

func (x *EncryptDataRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *EncryptDataRequest) GetEncryptMetadata() *EncryptMetadata {
	if x != nil {
		return x.EncryptMetadata
	}
	return nil
}

func (x *EncryptDataRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EncryptDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext     []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	CipherMetadata *CipherMetadata        `protobuf:"bytes,2,opt,name=cipherMetadata,proto3" json:"cipherMetadata,omitempty"`
	Metadata       *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Descriptor_    *CryptoDescriptor      `protobuf:"bytes,4,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EncryptDataResponse) Reset() {
	*x = EncryptDataResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptDataResponse) ProtoMessage() {}

func (x *EncryptDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptDataResponse.ProtoReflect.Descriptor instead.
func (*EncryptDataResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{19}
}

func (x *EncryptDataResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptDataResponse) GetCipherMetadata() *CipherMetadata {
	if x != nil {
		return x.CipherMetadata
	}
	return nil
}

func (x *EncryptDataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EncryptDataResponse) GetDescriptor_() *CryptoDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

// DecryptData request and response messages
type DecryptDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Profile         string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	KeySource       *KeySource             `protobuf:"bytes,2,opt,name=keySource,proto3" json:"keySource,omitempty"`
	Ciphertext      []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	DecryptMetadata *DecryptMetadata       `protobuf:"bytes,4,opt,name=decryptMetadata,proto3" json:"decryptMetadata,omitempty"`
	Metadata        *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecryptDataRequest) Reset() {
	*x = DecryptDataRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptDataRequest) ProtoMessage() {}

func (x *DecryptDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptDataRequest.ProtoReflect.Descriptor instead.
func (*DecryptDataRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{20}
}

func (x *DecryptDataRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *DecryptDataRequest) GetKeySource() *KeySource {
	if x != nil {
		return x.KeySource
	}
	return nil
}

func (x *DecryptDataRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecryptDataRequest) GetDecryptMetadata() *DecryptMetadata {
	if x != nil {
		return x.DecryptMetadata
	}
	return nil
}

func (x *DecryptDataRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DecryptDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptDataResponse) Reset() {
	*x = DecryptDataResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptDataResponse) ProtoMessage() {}

func (x *DecryptDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptDataResponse.ProtoReflect.Descriptor instead.
func (*DecryptDataResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{21}
}

func (x *DecryptDataResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *DecryptDataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Benchmark request and response messages
type BenchmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BenchmarkRequest) Reset() {
	*x = BenchmarkRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkRequest) ProtoMessage() {}

func (x *BenchmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkRequest.ProtoReflect.Descriptor instead.
func (*BenchmarkRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{22}
}

func (x *BenchmarkRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BenchmarkResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BenchmarkResults string                 `protobuf:"bytes,1,opt,name=benchmarkResults,proto3" json:"benchmarkResults,omitempty"`
	Metadata         *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BenchmarkResponse) Reset() {
	*x = BenchmarkResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkResponse) ProtoMessage() {}

func (x *BenchmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkResponse.ProtoReflect.Descriptor instead.
func (*BenchmarkResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{23}
}

func (x *BenchmarkResponse) GetBenchmarkResults() string {
	if x != nil {
		return x.BenchmarkResults
	}
	return ""
}

func (x *BenchmarkResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// FakeEndpoint request and response messages
type FakeEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakeEndpointRequest) Reset() {
	*x = FakeEndpointRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeEndpointRequest) ProtoMessage() {}

func (x *FakeEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeEndpointRequest.ProtoReflect.Descriptor instead.
func (*FakeEndpointRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{24}
}

func (x *FakeEndpointRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FakeEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakeEndpointResponse) Reset() {
	*x = FakeEndpointResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeEndpointResponse) ProtoMessage() {}

func (x *FakeEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeEndpointResponse.ProtoReflect.Descriptor instead.
func (*FakeEndpointResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{25}
}

func (x *FakeEndpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FakeEndpointResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_protobuf_messages_proto protoreflect.FileDescriptor

const file_protobuf_messages_proto_rawDesc = "" +
	"\n" +
	"\x17protobuf/messages.proto\x12\fCryptoBroker\"\xc9\x01\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12G\n" +
	"\vdeprecation\x18\x02 \x01(\v2 .CryptoBroker.DeprecationWarningH\x00R\vdeprecation\x88\x01\x01\x12C\n" +
	"\ftraceContext\x18\x03 \x01(\v2\x1a.CryptoBroker.TraceContextH\x01R\ftraceContext\x88\x01\x01B\x0e\n" +
	"\f_deprecationB\x0f\n" +
	"\r_traceContext\"h\n" +
	"\x10CryptoDescriptor\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\"\x84\x02\n" +
	"\x12DeprecationWarning\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12#\n" +
	"\n" +
	"replacedBy\x18\x02 \x01(\tH\x00R\n" +
	"replacedBy\x88\x01\x01\x12-\n" +
	"\x0fdeprecatedSince\x18\x03 \x01(\tH\x01R\x0fdeprecatedSince\x88\x01\x01\x12%\n" +
	"\vremoveAfter\x18\x04 \x01(\tH\x02R\vremoveAfter\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x05 \x01(\tH\x03R\x06reason\x88\x01\x01B\r\n" +
	"\v_replacedByB\x12\n" +
	"\x10_deprecatedSinceB\x0e\n" +
	"\f_removeAfterB\t\n" +
	"\a_reason\"\xa6\x01\n" +
	"\fTraceContext\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x16\n" +
	"\x06spanId\x18\x02 \x01(\tR\x06spanId\x12\x1e\n" +
	"\n" +
	"traceFlags\x18\x03 \x01(\tR\n" +
	"traceFlags\x12\x1e\n" +
	"\n" +
	"traceState\x18\x04 \x01(\tR\n" +
	"traceState\x12$\n" +
	"\rcorrelationId\x18\x05 \x01(\tR\rcorrelationId\"G\n" +
	"\tKeySource\x12\x16\n" +
	"\x05keyId\x18\x01 \x01(\tH\x00R\x05keyId\x12\x18\n" +
	"\x06rawKey\x18\x02 \x01(\fH\x00R\x06rawKeyB\b\n" +
	"\x06source\"\x91\x01\n" +
	"\rSignKeySource\x121\n" +
	"\x06single\x18\x01 \x01(\v2\x17.CryptoBroker.KeySourceH\x00R\x06single\x12C\n" +
	"\rcomponentKeys\x18\x02 \x01(\v2\x1b.CryptoBroker.ComponentKeysH\x00R\rcomponentKeysB\b\n" +
	"\x06source\"<\n" +
	"\rComponentKeys\x12+\n" +
	"\x04keys\x18\x01 \x03(\v2\x17.CryptoBroker.KeySourceR\x04keys\"F\n" +
	"\x0fEncryptMetadata\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x15\n" +
	"\x03aad\x18\x02 \x01(\fH\x00R\x03aad\x88\x01\x01B\x06\n" +
	"\x04_aad\"\x89\x01\n" +
	"\x0eCipherMetadata\x12\x19\n" +
	"\x05keyId\x18\x01 \x01(\tH\x00R\x05keyId\x88\x01\x01\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x15\n" +
	"\x03aad\x18\x03 \x01(\fH\x01R\x03aad\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\x04 \x01(\fH\x02R\x03tag\x88\x01\x01B\b\n" +
	"\x06_keyIdB\x06\n" +
	"\x04_aadB\x06\n" +
	"\x04_tag\"e\n" +
	"\x0fDecryptMetadata\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x15\n" +
	"\x03aad\x18\x02 \x01(\fH\x00R\x03aad\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\x03 \x01(\fH\x01R\x03tag\x88\x01\x01B\x06\n" +
	"\x04_aadB\x06\n" +
	"\x04_tag\"\xb9\x01\n" +
	"\x0fHashDataRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12B\n" +
	"\foutputFormat\x18\x04 \x01(\x0e2\x1e.CryptoBroker.HashOutputFormatR\foutputFormat\"\x85\x02\n" +
	"\x10HashDataResponse\x12$\n" +
	"\rhashAlgorithm\x18\x02 \x01(\tR\rhashAlgorithm\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12$\n" +
	"\fhashValueHex\x18\x04 \x01(\tH\x00R\fhashValueHex\x12$\n" +
	"\fhashValueRaw\x18\x05 \x01(\fH\x00R\fhashValueRaw\x12>\n" +
	"\n" +
	"descriptor\x18\x06 \x01(\v2\x1e.CryptoBroker.CryptoDescriptorR\n" +
	"descriptorB\v\n" +
	"\thashValue\"\xd6\x03\n" +
	"\x16SignCertificateRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x10\n" +
	"\x03csr\x18\x02 \x01(\tR\x03csr\x12\"\n" +
	"\fcaPrivateKey\x18\x03 \x01(\tR\fcaPrivateKey\x12\x16\n" +
	"\x06caCert\x18\x04 \x01(\tR\x06caCert\x122\n" +
	"\bmetadata\x18\x05 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12+\n" +
	"\x0evalidNotBefore\x18\x06 \x01(\x04H\x00R\x0evalidNotBefore\x88\x01\x01\x12)\n" +
	"\rvalidNotAfter\x18\a \x01(\x04H\x01R\rvalidNotAfter\x88\x01\x01\x12\x1d\n" +
	"\asubject\x18\b \x01(\tH\x02R\asubject\x88\x01\x01\x124\n" +
	"\x15crlDistributionPoints\x18\t \x03(\tR\x15crlDistributionPoints\x12B\n" +
	"\foutputFormat\x18\n" +
	" \x01(\x0e2\x1e.CryptoBroker.SignOutputFormatR\foutputFormatB\x11\n" +
	"\x0f_validNotBeforeB\x10\n" +
	"\x0e_validNotAfterB\n" +
	"\n" +
	"\b_subject\"\xca\x01\n" +
	"\x17SignCertificateResponse\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12\x12\n" +
	"\x03pem\x18\x03 \x01(\tH\x00R\x03pem\x12\x12\n" +
	"\x03der\x18\x04 \x01(\fH\x00R\x03der\x12>\n" +
	"\n" +
	"descriptor\x18\x05 \x01(\v2\x1e.CryptoBroker.CryptoDescriptorR\n" +
	"descriptorB\x13\n" +
	"\x11signedCertificate\"\x92\x02\n" +
	"\x0fSignDataRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x129\n" +
	"\tkeySource\x18\x02 \x01(\v2\x1b.CryptoBroker.SignKeySourceR\tkeySource\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12L\n" +
	"\x0fsignatureFormat\x18\x04 \x01(\x0e2\x1d.CryptoBroker.SignatureFormatH\x00R\x0fsignatureFormat\x88\x01\x01\x122\n" +
	"\bmetadata\x18\x05 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadataB\x12\n" +
	"\x10_signatureFormat\"\xa4\x01\n" +
	"\x10SignDataResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12>\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\v2\x1e.CryptoBroker.CryptoDescriptorR\n" +
	"descriptor\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"\xb2\x02\n" +
	"\x11VerifyDataRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x129\n" +
	"\tkeySource\x18\x02 \x01(\v2\x1b.CryptoBroker.SignKeySourceR\tkeySource\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12L\n" +
	"\x0fsignatureFormat\x18\x05 \x01(\x0e2\x1d.CryptoBroker.SignatureFormatH\x00R\x0fsignatureFormat\x88\x01\x01\x122\n" +
	"\bmetadata\x18\x06 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadataB\x12\n" +
	"\x10_signatureFormat\"^\n" +
	"\x12VerifyDataResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"\x80\x02\n" +
	"\x12EncryptDataRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x125\n" +
	"\tkeySource\x18\x02 \x01(\v2\x17.CryptoBroker.KeySourceR\tkeySource\x12\x1c\n" +
	"\tplaintext\x18\x03 \x01(\fR\tplaintext\x12G\n" +
	"\x0fencryptMetadata\x18\x04 \x01(\v2\x1d.CryptoBroker.EncryptMetadataR\x0fencryptMetadata\x122\n" +
	"\bmetadata\x18\x05 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"\xef\x01\n" +
	"\x13EncryptDataResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12D\n" +
	"\x0ecipherMetadata\x18\x02 \x01(\v2\x1c.CryptoBroker.CipherMetadataR\x0ecipherMetadata\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\x12>\n" +
	"\n" +
	"descriptor\x18\x04 \x01(\v2\x1e.CryptoBroker.CryptoDescriptorR\n" +
	"descriptor\"\x82\x02\n" +
	"\x12DecryptDataRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x125\n" +
	"\tkeySource\x18\x02 \x01(\v2\x17.CryptoBroker.KeySourceR\tkeySource\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\x12G\n" +
	"\x0fdecryptMetadata\x18\x04 \x01(\v2\x1d.CryptoBroker.DecryptMetadataR\x0fdecryptMetadata\x122\n" +
	"\bmetadata\x18\x05 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"g\n" +
	"\x13DecryptDataResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"F\n" +
	"\x10BenchmarkRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"s\n" +
	"\x11BenchmarkResponse\x12*\n" +
	"\x10benchmarkResults\x18\x01 \x01(\tR\x10benchmarkResults\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"I\n" +
	"\x13FakeEndpointRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata\"d\n" +
	"\x14FakeEndpointResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.CryptoBroker.MetadataR\bmetadata*$\n" +
	"\x10HashOutputFormat\x12\a\n" +
	"\x03HEX\x10\x00\x12\a\n" +
	"\x03RAW\x10\x01*$\n" +
	"\x10SignOutputFormat\x12\a\n" +
	"\x03DER\x10\x00\x12\a\n" +
	"\x03PEM\x10\x01*]\n" +
	"\x0fSignatureFormat\x12\x11\n" +
	"\rSIGNATURE_RAW\x10\x00\x12\x11\n" +
	"\rSIGNATURE_DER\x10\x01\x12\x11\n" +
	"\rSIGNATURE_PEM\x10\x02\x12\x11\n" +
	"\rSIGNATURE_CMS\x10\x03*\x90\x01\n" +
	"\x10MessageSizeLimit\x12\"\n" +
	"\x1eMESSAGE_SIZE_LIMIT_UNSPECIFIED\x10\x00\x12+\n" +
	"$MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES\x10\x80\x80\x80\x01\x12+\n" +
	"%MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES\x10\x80\x80@*\xb8\b\n" +
	"\rPayloadLimits\x12\x1e\n" +
	"\x1aPAYLOAD_LIMITS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1ePAYLOAD_LIMITS_PROFILE_MAX_LEN\x10@\x12'\n" +
	"\"PAYLOAD_LIMITS_METADATA_ID_MAX_LEN\x10\x80\x01\x12,\n" +
	"&PAYLOAD_LIMITS_HASH_DATA_INPUT_MAX_LEN\x10\x80\x80@\x121\n" +
	"+PAYLOAD_LIMITS_SIGN_CERTIFICATE_CSR_MAX_LEN\x10\x80\x80\x04\x12<\n" +
	"6PAYLOAD_LIMITS_SIGN_CERTIFICATE_CA_PRIVATE_KEY_MAX_LEN\x10\x80\x80\x04\x125\n" +
	"/PAYLOAD_LIMITS_SIGN_CERTIFICATE_CA_CERT_MAX_LEN\x10\x80\x80\x04\x124\n" +
	"/PAYLOAD_LIMITS_SIGN_CERTIFICATE_SUBJECT_MAX_LEN\x10\x80\b\x12;\n" +
	"7PAYLOAD_LIMITS_SIGN_CERTIFICATE_DISTRIBUTION_POINTS_MAX\x10\x10\x12?\n" +
	":PAYLOAD_LIMITS_SIGN_CERTIFICATE_DISTRIBUTION_POINT_MAX_LEN\x10\x80\x10\x12@\n" +
	"<PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_KEYSOURCE_KEY_ID_MAX_LEN\x10@\x12A\n" +
	"=PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_KEYSOURCE_KEY_RAW_MAX_LEN\x10 \x124\n" +
	"0PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_DATA_MAX_LEN\x10@\x125\n" +
	"1PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_NONCE_MAX_LEN\x10 \x123\n" +
	"/PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_TAG_MAX_LEN\x10 \x123\n" +
	"/PAYLOAD_LIMITS_ENCRYPT_DECRYPT_DATA_AAD_MAX_LEN\x10 \x12#\n" +
	"\x1fPAYLOAD_LIMITS_TRACE_ID_MAX_LEN\x10 \x12(\n" +
	"$PAYLOAD_LIMITS_TRACE_SPAN_ID_MAX_LEN\x10\x10\x12&\n" +
	"\"PAYLOAD_LIMITS_TRACE_FLAGS_MAX_LEN\x10\x02\x12'\n" +
	"\"PAYLOAD_LIMITS_TRACE_STATE_MAX_LEN\x10\x80\x04\x120\n" +
	"+PAYLOAD_LIMITS_TRACE_CORRELATION_ID_MAX_LEN\x10\x80\x01\x1a\x02\x10\x012\xfb\x03\n" +
	"\n" +
	"CryptoGrpc\x12I\n" +
	"\bHashData\x12\x1d.CryptoBroker.HashDataRequest\x1a\x1e.CryptoBroker.HashDataResponse\x12^\n" +
	"\x0fSignCertificate\x12$.CryptoBroker.SignCertificateRequest\x1a%.CryptoBroker.SignCertificateResponse\x12I\n" +
	"\bSignData\x12\x1d.CryptoBroker.SignDataRequest\x1a\x1e.CryptoBroker.SignDataResponse\x12O\n" +
	"\n" +
	"VerifyData\x12\x1f.CryptoBroker.VerifyDataRequest\x1a .CryptoBroker.VerifyDataResponse\x12R\n" +
	"\vEncryptData\x12 .CryptoBroker.EncryptDataRequest\x1a!.CryptoBroker.EncryptDataResponse\x12R\n" +
	"\vDecryptData\x12 .CryptoBroker.DecryptDataRequest\x1a!.CryptoBroker.DecryptDataResponse2\xb4\x01\n" +
	"\rCryptoGrpcDev\x12L\n" +
	"\tBenchmark\x12\x1e.CryptoBroker.BenchmarkRequest\x1a\x1f.CryptoBroker.BenchmarkResponse\x12U\n" +
	"\fFakeEndpoint\x12!.CryptoBroker.FakeEndpointRequest\x1a\".CryptoBroker.FakeEndpointResponseB\x13Z\x11internal/protobufb\x06proto3"

var (
	file_protobuf_messages_proto_rawDescOnce sync.Once
	file_protobuf_messages_proto_rawDescData []byte
)

func file_protobuf_messages_proto_rawDescGZIP() []byte {
	file_protobuf_messages_proto_rawDescOnce.Do(func() {
		file_protobuf_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_messages_proto_rawDesc), len(file_protobuf_messages_proto_rawDesc)))
	})
	return file_protobuf_messages_proto_rawDescData
}

var file_protobuf_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_protobuf_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_protobuf_messages_proto_goTypes = []any{
	(HashOutputFormat)(0),           // 0: CryptoBroker.HashOutputFormat
	(SignOutputFormat)(0),           // 1: CryptoBroker.SignOutputFormat
	(SignatureFormat)(0),            // 2: CryptoBroker.SignatureFormat
	(MessageSizeLimit)(0),           // 3: CryptoBroker.MessageSizeLimit
	(PayloadLimits)(0),              // 4: CryptoBroker.PayloadLimits
	(*Metadata)(nil),                // 5: CryptoBroker.Metadata
	(*CryptoDescriptor)(nil),        // 6: CryptoBroker.CryptoDescriptor
	(*DeprecationWarning)(nil),      // 7: CryptoBroker.DeprecationWarning
	(*TraceContext)(nil),            // 8: CryptoBroker.TraceContext
	(*KeySource)(nil),               // 9: CryptoBroker.KeySource
	(*SignKeySource)(nil),           // 10: CryptoBroker.SignKeySource
	(*ComponentKeys)(nil),           // 11: CryptoBroker.ComponentKeys
	(*EncryptMetadata)(nil),         // 12: CryptoBroker.EncryptMetadata
	(*CipherMetadata)(nil),          // 13: CryptoBroker.CipherMetadata
	(*DecryptMetadata)(nil),         // 14: CryptoBroker.DecryptMetadata
	(*HashDataRequest)(nil),         // 15: CryptoBroker.HashDataRequest
	(*HashDataResponse)(nil),        // 16: CryptoBroker.HashDataResponse
	(*SignCertificateRequest)(nil),  // 17: CryptoBroker.SignCertificateRequest
	(*SignCertificateResponse)(nil), // 18: CryptoBroker.SignCertificateResponse
	(*SignDataRequest)(nil),         // 19: CryptoBroker.SignDataRequest
	(*SignDataResponse)(nil),        // 20: CryptoBroker.SignDataResponse
	(*VerifyDataRequest)(nil),       // 21: CryptoBroker.VerifyDataRequest
	(*VerifyDataResponse)(nil),      // 22: CryptoBroker.VerifyDataResponse
	(*EncryptDataRequest)(nil),      // 23: CryptoBroker.EncryptDataRequest
	(*EncryptDataResponse)(nil),     // 24: CryptoBroker.EncryptDataResponse
	(*DecryptDataRequest)(nil),      // 25: CryptoBroker.DecryptDataRequest
	(*DecryptDataResponse)(nil),     // 26: CryptoBroker.DecryptDataResponse
	(*BenchmarkRequest)(nil),        // 27: CryptoBroker.BenchmarkRequest
	(*BenchmarkResponse)(nil),       // 28: CryptoBroker.BenchmarkResponse
	(*FakeEndpointRequest)(nil),     // 29: CryptoBroker.FakeEndpointRequest
	(*FakeEndpointResponse)(nil),    // 30: CryptoBroker.FakeEndpointResponse
}
var file_protobuf_messages_proto_depIdxs = []int32{
	7,  // 0: CryptoBroker.Metadata.deprecation:type_name -> CryptoBroker.DeprecationWarning
	8,  // 1: CryptoBroker.Metadata.traceContext:type_name -> CryptoBroker.TraceContext
	9,  // 2: CryptoBroker.SignKeySource.single:type_name -> CryptoBroker.KeySource
	11, // 3: CryptoBroker.SignKeySource.componentKeys:type_name -> CryptoBroker.ComponentKeys
	9,  // 4: CryptoBroker.ComponentKeys.keys:type_name -> CryptoBroker.KeySource
	5,  // 5: CryptoBroker.HashDataRequest.metadata:type_name -> CryptoBroker.Metadata
	0,  // 6: CryptoBroker.HashDataRequest.outputFormat:type_name -> CryptoBroker.HashOutputFormat
	5,  // 7: CryptoBroker.HashDataResponse.metadata:type_name -> CryptoBroker.Metadata
	6,  // 8: CryptoBroker.HashDataResponse.descriptor:type_name -> CryptoBroker.CryptoDescriptor
	5,  // 9: CryptoBroker.SignCertificateRequest.metadata:type_name -> CryptoBroker.Metadata
	1,  // 10: CryptoBroker.SignCertificateRequest.outputFormat:type_name -> CryptoBroker.SignOutputFormat
	5,  // 11: CryptoBroker.SignCertificateResponse.metadata:type_name -> CryptoBroker.Metadata
	6,  // 12: CryptoBroker.SignCertificateResponse.descriptor:type_name -> CryptoBroker.CryptoDescriptor
	10, // 13: CryptoBroker.SignDataRequest.keySource:type_name -> CryptoBroker.SignKeySource
	2,  // 14: CryptoBroker.SignDataRequest.signatureFormat:type_name -> CryptoBroker.SignatureFormat
	5,  // 15: CryptoBroker.SignDataRequest.metadata:type_name -> CryptoBroker.Metadata
	6,  // 16: CryptoBroker.SignDataResponse.descriptor:type_name -> CryptoBroker.CryptoDescriptor
	5,  // 17: CryptoBroker.SignDataResponse.metadata:type_name -> CryptoBroker.Metadata
	10, // 18: CryptoBroker.VerifyDataRequest.keySource:type_name -> CryptoBroker.SignKeySource
	2,  // 19: CryptoBroker.VerifyDataRequest.signatureFormat:type_name -> CryptoBroker.SignatureFormat
	5,  // 20: CryptoBroker.VerifyDataRequest.metadata:type_name -> CryptoBroker.Metadata
	5,  // 21: CryptoBroker.VerifyDataResponse.metadata:type_name -> CryptoBroker.Metadata
	9,  // 22: CryptoBroker.EncryptDataRequest.keySource:type_name -> CryptoBroker.KeySource
	12, // 23: CryptoBroker.EncryptDataRequest.encryptMetadata:type_name -> CryptoBroker.EncryptMetadata
	5,  // 24: CryptoBroker.EncryptDataRequest.metadata:type_name -> CryptoBroker.Metadata
	13, // 25: CryptoBroker.EncryptDataResponse.cipherMetadata:type_name -> CryptoBroker.CipherMetadata
	5,  // 26: CryptoBroker.EncryptDataResponse.metadata:type_name -> CryptoBroker.Metadata
	6,  // 27: CryptoBroker.EncryptDataResponse.descriptor:type_name -> CryptoBroker.CryptoDescriptor
	9,  // 28: CryptoBroker.DecryptDataRequest.keySource:type_name -> CryptoBroker.KeySource
	14, // 29: CryptoBroker.DecryptDataRequest.decryptMetadata:type_name -> CryptoBroker.DecryptMetadata
	5,  // 30: CryptoBroker.DecryptDataRequest.metadata:type_name -> CryptoBroker.Metadata
	5,  // 31: CryptoBroker.DecryptDataResponse.metadata:type_name -> CryptoBroker.Metadata
	5,  // 32: CryptoBroker.BenchmarkRequest.metadata:type_name -> CryptoBroker.Metadata
	5,  // 33: CryptoBroker.BenchmarkResponse.metadata:type_name -> CryptoBroker.Metadata
	5,  // 34: CryptoBroker.FakeEndpointRequest.metadata:type_name -> CryptoBroker.Metadata
	5,  // 35: CryptoBroker.FakeEndpointResponse.metadata:type_name -> CryptoBroker.Metadata
	15, // 36: CryptoBroker.CryptoGrpc.HashData:input_type -> CryptoBroker.HashDataRequest
	17, // 37: CryptoBroker.CryptoGrpc.SignCertificate:input_type -> CryptoBroker.SignCertificateRequest
	19, // 38: CryptoBroker.CryptoGrpc.SignData:input_type -> CryptoBroker.SignDataRequest
	21, // 39: CryptoBroker.CryptoGrpc.VerifyData:input_type -> CryptoBroker.VerifyDataRequest
	23, // 40: CryptoBroker.CryptoGrpc.EncryptData:input_type -> CryptoBroker.EncryptDataRequest
	25, // 41: CryptoBroker.CryptoGrpc.DecryptData:input_type -> CryptoBroker.DecryptDataRequest
	27, // 42: CryptoBroker.CryptoGrpcDev.Benchmark:input_type -> CryptoBroker.BenchmarkRequest
	29, // 43: CryptoBroker.CryptoGrpcDev.FakeEndpoint:input_type -> CryptoBroker.FakeEndpointRequest
	16, // 44: CryptoBroker.CryptoGrpc.HashData:output_type -> CryptoBroker.HashDataResponse
	18, // 45: CryptoBroker.CryptoGrpc.SignCertificate:output_type -> CryptoBroker.SignCertificateResponse
	20, // 46: CryptoBroker.CryptoGrpc.SignData:output_type -> CryptoBroker.SignDataResponse
	22, // 47: CryptoBroker.CryptoGrpc.VerifyData:output_type -> CryptoBroker.VerifyDataResponse
	24, // 48: CryptoBroker.CryptoGrpc.EncryptData:output_type -> CryptoBroker.EncryptDataResponse
	26, // 49: CryptoBroker.CryptoGrpc.DecryptData:output_type -> CryptoBroker.DecryptDataResponse
	28, // 50: CryptoBroker.CryptoGrpcDev.Benchmark:output_type -> CryptoBroker.BenchmarkResponse
	30, // 51: CryptoBroker.CryptoGrpcDev.FakeEndpoint:output_type -> CryptoBroker.FakeEndpointResponse
	44, // [44:52] is the sub-list for method output_type
	36, // [36:44] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_protobuf_messages_proto_init() }
func file_protobuf_messages_proto_init() {
	if File_protobuf_messages_proto != nil {
		return
	}
	file_protobuf_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[2].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[4].OneofWrappers = []any{
		(*KeySource_KeyId)(nil),
		(*KeySource_RawKey)(nil),
	}
	file_protobuf_messages_proto_msgTypes[5].OneofWrappers = []any{
		(*SignKeySource_Single)(nil),
		(*SignKeySource_ComponentKeys)(nil),
	}
	file_protobuf_messages_proto_msgTypes[7].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[8].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[9].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[11].OneofWrappers = []any{
		(*HashDataResponse_HashValueHex)(nil),
		(*HashDataResponse_HashValueRaw)(nil),
	}
	file_protobuf_messages_proto_msgTypes[12].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[13].OneofWrappers = []any{
		(*SignCertificateResponse_Pem)(nil),
		(*SignCertificateResponse_Der)(nil),
	}
	file_protobuf_messages_proto_msgTypes[14].OneofWrappers = []any{}
	file_protobuf_messages_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_messages_proto_rawDesc), len(file_protobuf_messages_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobuf_messages_proto_goTypes,
		DependencyIndexes: file_protobuf_messages_proto_depIdxs,
		EnumInfos:         file_protobuf_messages_proto_enumTypes,
		MessageInfos:      file_protobuf_messages_proto_msgTypes,
	}.Build()
	File_protobuf_messages_proto = out.File
	file_protobuf_messages_proto_goTypes = nil
	file_protobuf_messages_proto_depIdxs = nil
}
