name: Create-Release-Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. 1.3.0)'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

permissions: {}

jobs:
  changelog:
    name: Update changelog
    permissions:
      contents: write # for pushing updated changelog and tag to repo
    runs-on: ubuntu-latest
    environment: DEPLOYMENT

    steps:
      - name: Create GitHub app token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.DEPLOYMENT_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Use git-cliff for changelog generation, create git tag, push to repo
        uses: open-crypto-broker/.github/actions/git-cliff@main # nolint # zizmor: ignore[unpinned-uses]
        with:
          ref_name: ${{ github.ref_name }}
          version: ${{ github.event.inputs.version }}
          token: ${{ steps.app-token.outputs.token }}
