name: Workflow Lint

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  lint:
    uses: open-crypto-broker/.github/.github/workflows/workflow-lint.yaml@main # nolint # zizmor: ignore[unpinned-uses]

