---
# Crypto Profiles Catalogue
#
# This file defines multiple cryptographic policy profiles used by the Crypto Broker Server.
# Each profile constrains algorithms, hash functions and key size ranges for certificate
# generation and data hashing operations (APIs mapped in internal/profile/*).
#
# Rationale / Standards Referenced (non-exhaustive):
#   * FIPS 140-3: Security Requirements for Cryptographic Modules
#   * NIST SP 800-131A Rev.2: Transitioning the Use of Cryptographic Algorithms and Key Lengths
#   * NIST SP 800-57 Part 1 Rev.5: Recommendation for Key Management (key length equivalence)
#   * NCA Saudi Arabia: National Cryptographic Standards (NCS 1:2020)
#
# Notes:
#   * Only algorithms supported by the current implementation (see internal/c10y/alg.go) can be declared.
#   * ECDSA key sizes in constraints refer to nominal curve bit size (P-256, P-384, P-521 etc.).
#   * Where standards allow broader sets (e.g., Ed25519, X25519, SHA-3 variants for signatures), they
#     are omitted if not yet implemented in the codebase.
#   * Validity offsets express relative durations: NotBefore = now + offset; negative value means
#     backdating (accommodates clock skew). NotAfter = now + offset.


# Default profile kept minimal – broad demo; not tied to a single external standard.
#   Reasoning: Showcases widest hash (sha3-512) and high-strength hash/sign combo for testing.

- Name: Default
  Settings:
    CryptoLibrary: native
  API:
    HashData:
      HashAlg: sha3-512
    SignCertificate:
      SignAlg: ecdsa
      HashAlg: sha-512
      Validity:
        ValidNotBeforeOffset: -1h
        ValidNotAfterOffset: 8760h
      KeyConstraints:
        Subject:
          RSA:
            MinKeySize: 2048
            MaxKeySize: 4096
          ECDSA:
            MinKeySize: 256
            MaxKeySize: 521
        Issuer:
          RSA:
            MinKeySize: 3072
            MaxKeySize: 8192
          ECDSA:
            MinKeySize: 384
            MaxKeySize: 521
      KeyUsage:         [digitalSignature, keyEncipherment]
      ExtendedKeyUsage: [clientAuth]
      BasicConstraints:
        CA: false


# KSA NCA MODERATE
#   Goal: Provide moderate security requirements equivalent to 128-bit security level.
#   Hash: SHA-384 and SHA-512/256, SHA3-256, SHA3-384, SHAKE128, SHAKE256.
#   RSA:  >= 3072-bit  
#   ECDSA: 256-bit - 384-bit (curve P-256, P-384)
#   Reference: NCS_1_2020 Page 12 and 16

- Name: KSA-MODERATE-2020
  Settings:
    CryptoLibrary: native
  API:
    HashData:
      HashAlg: sha-384          
    SignCertificate:
      SignAlg: rsa
      HashAlg: sha-384
      Validity:
        ValidNotBeforeOffset: -1h
        ValidNotAfterOffset: 8760h
      KeyConstraints:
        Subject:
          RSA:
            MinKeySize: 3072    
            MaxKeySize: 8192
          ECDSA:
            MinKeySize: 256
            MaxKeySize: 384
        Issuer:
          RSA:
            MinKeySize: 3072
            MaxKeySize: 8192
          ECDSA:
            MinKeySize: 256
            MaxKeySize: 384
      KeyUsage:         [digitalSignature, keyEncipherment]
      ExtendedKeyUsage: [clientAuth]
      BasicConstraints:
        CA: false


# KSA NCA ADVANCED
#   Goal: Provide advanced security requirements equivalent to 256-bit security level.
#   Hash: SHA3-512
#   RSA:  Not accepted for ADVANCED level.
#   ECDSA: 512-bit (curve P-521)
#   Reference: NCS_1_2020 Page 12 and 16

- Name: KSA-ADVANCED-2020
  Settings:
    CryptoLibrary: native
  API:
    HashData:
      HashAlg: sha3-512          
    SignCertificate:
      SignAlg: ecdsa
      HashAlg: sha3-512
      Validity:
        ValidNotBeforeOffset: -1h
        ValidNotAfterOffset: 8760h
      KeyConstraints:
        Subject:
          #RSA: # Not accepted
          #  MinKeySize: 8192    
          #  MaxKeySize: 8192
          ECDSA:
            MinKeySize: 521
            MaxKeySize: 521
        Issuer:
          #RSA: # Not accepted
          #  MinKeySize: 8192
          #  MaxKeySize: 8192
          ECDSA:
            MinKeySize: 521
            MaxKeySize: 521
      KeyUsage:         [digitalSignature, keyEncipherment]
      ExtendedKeyUsage: [clientAuth]
      BasicConstraints:
        CA: false


# FIPS-140-3 Baseline
#   Goal: Provide 128-bit security.
#   Hash: sha-256, sha-512/256, sha3-256.
#   RSA: >= 3072 bit .
#   ECDSA: 256-bit - 383-bit
#   Reference: NIST_SP_800_57, Table 2 on Page 54-55, Table 3 on Page 56

- Name: FIPS-140-3-Baseline
  Settings:
    CryptoLibrary: native
  API:
    HashData:
      HashAlg: sha-256
    SignCertificate:
      SignAlg: rsa
      HashAlg: sha-256
      Validity:
        ValidNotBeforeOffset: -1h
        ValidNotAfterOffset: 8760h
      KeyConstraints:
        Subject:
          RSA:
            MinKeySize: 3072
            MaxKeySize: 7680
          ECDSA:
            MinKeySize: 256
            MaxKeySize: 383
        Issuer:
          RSA:
            MinKeySize: 3072
            MaxKeySize: 7680
          ECDSA:
            MinKeySize: 256
            MaxKeySize: 383
      KeyUsage:         [digitalSignature, keyEncipherment]
      ExtendedKeyUsage: [clientAuth]
      BasicConstraints:
        CA: false

# FIPS-140-3 Medium
#   Goal: Provide 192-bit security.
#   Hash: sha-384, sha3-384.
#   RSA: >= 7680 bit.
#   ECDSA: 384-bit - 511-bit
#   Reference: NIST_SP_800_57, Table 2 on Page 54-55, Table 3 on Page 56

- Name: FIPS-140-3-Medium
  Settings:
    CryptoLibrary: native
  API:
    HashData:
      HashAlg: sha-384
    SignCertificate:
      SignAlg: rsa
      HashAlg: sha-384
      Validity:
        ValidNotBeforeOffset: -1h
        ValidNotAfterOffset: 8760h
      KeyConstraints:
        Subject:
          RSA:
            MinKeySize: 7680
            MaxKeySize: 15360
          ECDSA:
            MinKeySize: 384
            MaxKeySize: 511
        Issuer:
          RSA:
            MinKeySize: 7680
            MaxKeySize: 15360
          ECDSA:
            MinKeySize: 384
            MaxKeySize: 511
      KeyUsage:         [digitalSignature, keyEncipherment]
      ExtendedKeyUsage: [clientAuth]
      BasicConstraints:
        CA: false

# FIPS-140-3 Strict
#   Goal: Provide 256-bit security.
#   Hash: sha-512, sha3-512.
#   RSA: 15380-bit
#   ECDSA: >= 512-bit
#   Reference: NIST_SP_800_57, Table 2 on Page 54-55, Table 3 on Page 56

- Name: FIPS-140-3-Strict
  Settings:
    CryptoLibrary: native
  API:
    HashData:
      HashAlg: sha-512
    SignCertificate:
      SignAlg: ecdsa
      HashAlg: sha-512
      Validity:
        ValidNotBeforeOffset: -1h
        ValidNotAfterOffset: 4380h
      KeyConstraints:
        Subject:
          RSA:
            MinKeySize: 15380
            MaxKeySize: 15380
          ECDSA:
            MinKeySize: 521
            MaxKeySize: 521
        Issuer:
          RSA:
            MinKeySize: 15380
            MaxKeySize: 15380
          ECDSA:
            MinKeySize: 521
            MaxKeySize: 521
      KeyUsage:         [digitalSignature]
      ExtendedKeyUsage: [clientAuth]
      BasicConstraints:
        CA: false



# References
#   [FIPS_140_3] FIPS 140-3 -- Security Requirements for Cryptographic Modules -- https://csrc.nist.gov/publications/detail/fips/140/3/final
#   [FIPS_186_5] FIPS 186-5 -- Digital Signature Standard (DSS) -- https://csrc.nist.gov/publications/detail/fips/186/5/final
#   [FIPS_180_4] FIPS PUB 180-4 -- Secure Hash Standard (SHS) -- https://csrc.nist.gov/publications/detail/fips/180/4/final
#   [FIPS_202] FIPS PUB 202 -- SHA-3 Standard: Permutation-Based Hash and Extendable-Output Functions -- https://csrc.nist.gov/publications/detail/fips/202/final
#   [NIST_SP_800_131A] NIST SP 800-131A Rev.2 -- Transitioning the Use of Cryptographic Algorithms and Key Lengths -- https://csrc.nist.gov/publications/detail/sp/800-131a/rev-2/final 
#   [NIST_SP_800_57] NIST SP 800-57 Part 1 Rev.5 -- Recommendation for Key Management: Part 1 - General -- https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final
#   [NCS_1_2020] NCS -1:2020 -- National Cryptographic Standards -- https://nca.gov.sa/ncs_en.pdf  
