---
# Default profile kept minimal – broad demo; not tied to a single external standard.
#   Reasoning: Showcases widest hash (sha3-512) and high-strength hash/sign combo for testing.
- Name: Default
  Settings:
    CryptoLibrary: native
  API:
    HashData:
      HashAlg: sha3-512
    SignCertificate:
      SignAlg: ecdsa
      HashAlg: sha-512
      Validity:
        ValidNotBeforeOffset: -1h
        ValidNotAfterOffset: 8760h
      KeyConstraints:
        Subject:
          RSA:
            MinKeySize: 2048
            MaxKeySize: 4096
          ECDSA:
            MinKeySize: 256
            MaxKeySize: 521
        Issuer:
          ECDSA:
            MinKeySize: 384
            MaxKeySize: 521
      KeyUsage:         [digitalSignature, keyEncipherment]
      ExtendedKeyUsage: [clientAuth]
      BasicConstraints:
        CA: false
